#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class DataContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public DataContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Annotation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Annotation> AnnotationSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Annotation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Campaign"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Campaign> CampaignSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Campaign>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Connection"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Connection> ConnectionSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Connection>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.CustomerAddress"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.CustomerAddress> CustomerAddressSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.CustomerAddress>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Email"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Email> EmailSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Email>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Lead"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Lead> LeadSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Lead>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Letter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Letter> LetterSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Letter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.List"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.List> ListSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.List>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.msdynmkt_topic"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.msdynmkt_topic> msdynmkt_topicSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.msdynmkt_topic>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_accounttype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_accounttype> new_accounttypeSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_accounttype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_attendeetype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_attendeetype> new_attendeetypeSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_attendeetype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_batch"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_batch> new_batchSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_batch>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_CMADiagnosticLog"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_CMADiagnosticLog> new_CMADiagnosticLogSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_CMADiagnosticLog>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_CMAFlowConfiguration"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_CMAFlowConfiguration> new_CMAFlowConfigurationSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_CMAFlowConfiguration>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_CMAFlowLog"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_CMAFlowLog> new_CMAFlowLogSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_CMAFlowLog>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_cmahexportchange"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_cmahexportchange> new_cmahexportchangeSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_cmahexportchange>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_CMALogConfiguration"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_CMALogConfiguration> new_CMALogConfigurationSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_CMALogConfiguration>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_cmamembershipdetail"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_cmamembershipdetail> new_cmamembershipdetailSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_cmamembershipdetail>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_CMATag"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_CMATag> new_CMATagSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_CMATag>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_codelookup"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_codelookup> new_codelookupSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_codelookup>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_contacttype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_contacttype> new_contacttypeSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_contacttype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_contactwidget"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_contactwidget> new_contactwidgetSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_contactwidget>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_customconfiguration"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_customconfiguration> new_customconfigurationSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_customconfiguration>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_discontinuedreason"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_discontinuedreason> new_discontinuedreasonSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_discontinuedreason>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_event"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_event> new_eventSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_event>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_eventattendee"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_eventattendee> new_eventattendeeSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_eventattendee>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_eventfollowup"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_eventfollowup> new_eventfollowupSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_eventfollowup>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_eventtype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_eventtype> new_eventtypeSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_eventtype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_grantprogram"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_grantprogram> new_grantprogramSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_grantprogram>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_grantsubmission"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_grantsubmission> new_grantsubmissionSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_grantsubmission>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_membercategoryxref"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_membercategoryxref> new_membercategoryxrefSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_membercategoryxref>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_membershipbenefit"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_membershipbenefit> new_membershipbenefitSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_membershipbenefit>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_membershippricingrule"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_membershippricingrule> new_membershippricingruleSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_membershippricingrule>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_onlineapplication"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_onlineapplication> new_onlineapplicationSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_onlineapplication>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_opportunitytype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_opportunitytype> new_opportunitytypeSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_opportunitytype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_opt"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_opt> new_optSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_opt>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_optmanagementscreen"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_optmanagementscreen> new_optmanagementscreenSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_optmanagementscreen>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_payment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_payment> new_paymentSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_payment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_physicianspecialty"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_physicianspecialty> new_physicianspecialtySet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_physicianspecialty>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_portaldocumentdownload"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_portaldocumentdownload> new_portaldocumentdownloadSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_portaldocumentdownload>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_psi"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_psi> new_psiSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_psi>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_psiobjective"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_psiobjective> new_psiobjectiveSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_psiobjective>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_sms"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_sms> new_smsSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_sms>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_specialty"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_specialty> new_specialtySet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_specialty>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_ssisauditrun"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_ssisauditrun> new_ssisauditrunSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_ssisauditrun>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_ssisauditrunerror"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_ssisauditrunerror> new_ssisauditrunerrorSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_ssisauditrunerror>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_ssisfailedregistration"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_ssisfailedregistration> new_ssisfailedregistrationSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_ssisfailedregistration>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_ssismissingevent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_ssismissingevent> new_ssismissingeventSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_ssismissingevent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_submittedquestion"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_submittedquestion> new_submittedquestionSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_submittedquestion>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_subscription"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_subscription> new_subscriptionSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_subscription>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_taxrate"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_taxrate> new_taxrateSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_taxrate>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_TopicCategory"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_TopicCategory> new_TopicCategorySet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_TopicCategory>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.new_transaction"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.new_transaction> new_transactionSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.new_transaction>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Opportunity"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Opportunity> OpportunitySet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Opportunity>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.OpportunityProduct"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.OpportunityProduct> OpportunityProductSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.OpportunityProduct>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.OpportunitySalesProcess"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.OpportunitySalesProcess> OpportunitySalesProcessSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.OpportunitySalesProcess>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.PhoneCall"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.PhoneCall> PhoneCallSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.PhoneCall>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.PriceLevel"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.PriceLevel> PriceLevelSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.PriceLevel>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Product"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Product> ProductSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Product>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.ProductAssociation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.ProductAssociation> ProductAssociationSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.ProductAssociation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.ProductPriceLevel"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.ProductPriceLevel> ProductPriceLevelSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.ProductPriceLevel>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.ProductSubstitute"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.ProductSubstitute> ProductSubstituteSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.ProductSubstitute>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Queue"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Queue> QueueSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Queue>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.QueueItem"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.QueueItem> QueueItemSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.QueueItem>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.SalesOrder"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.SalesOrder> SalesOrderSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.SalesOrder>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.SalesOrderDetail"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.SalesOrderDetail> SalesOrderDetailSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.SalesOrderDetail>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.SystemUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CMA.Extensions.Model.Task"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CMA.Extensions.Model.Task> TaskSet
		{
			get
			{
				return this.CreateQuery<CMA.Extensions.Model.Task>();
			}
		}
	}
}
#pragma warning restore CS1591
