#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Type of address for the customer, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum customeraddress_addresstypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BillTo = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ShipTo = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Primary = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Home = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Professional = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other1 = 100000008,
	}
	
	/// <summary>
	/// Freight terms for the customer address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum customeraddress_freighttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FOB = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoCharge = 2,
	}
	
	/// <summary>
	/// Method of shipment for the customer address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum customeraddress_shippingmethodcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Airborne = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DHL = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FedEx = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UPS = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostalMail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FullLoad = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillCall = 7,
	}
	
	/// <summary>
	/// Address and shipping information. Used to store additional addresses for an account or contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("customeraddress")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class CustomerAddress : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public CustomerAddress() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "customeraddress";
		
		public const string EntityLogicalCollectionName = "customeraddresses";
		
		public const string EntitySetName = "customeraddresses";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// OOTB Address Number field. Referenced in filter criteria for views and other logic related to membership processing, set programmatically when address is created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("addressnumber")]
		public System.Nullable<int> AddressNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("addressnumber");
			}
			set
			{
				this.OnPropertyChanging("AddressNumber");
				this.SetAttributeValue("addressnumber", value);
				this.OnPropertyChanged("AddressNumber");
			}
		}
		
		/// <summary>
		/// Exposed on member-facing manage address pages. Populated manually and programmatically (from Application submission/contact creation). Contact can only have one of each type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("addresstypecode")]
		public virtual customeraddress_addresstypecode? AddressTypeCode
		{
			get
			{
				return ((customeraddress_addresstypecode?)(EntityOptionSetEnum.GetEnum(this, "addresstypecode")));
			}
			set
			{
				this.OnPropertyChanging("AddressTypeCode");
				this.SetAttributeValue("addresstypecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("AddressTypeCode");
			}
		}
		
		/// <summary>
		/// Used to track an address's City component. Populated manually, as part of Canada Post API response, and/or through data normalization from submitted Application records.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("city")]
		public string City
		{
			get
			{
				return this.GetAttributeValue<string>("city");
			}
			set
			{
				this.OnPropertyChanging("City");
				this.SetAttributeValue("city", value);
				this.OnPropertyChanged("City");
			}
		}
		
		/// <summary>
		/// OOTB Address composite field. Not exposed on forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("composite")]
		public string Composite
		{
			get
			{
				return this.GetAttributeValue<string>("composite");
			}
			set
			{
				this.OnPropertyChanging("Composite");
				this.SetAttributeValue("composite", value);
				this.OnPropertyChanged("Composite");
			}
		}
		
		/// <summary>
		/// OOTB Country field, accepts text data entry. Not exposed on any forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("country")]
		public string Country
		{
			get
			{
				return this.GetAttributeValue<string>("country");
			}
			set
			{
				this.OnPropertyChanging("Country");
				this.SetAttributeValue("country", value);
				this.OnPropertyChanged("Country");
			}
		}
		
		/// <summary>
		/// OOTB field used to track county information. Not exposed on any forms within CRM or portal.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("county")]
		public string County
		{
			get
			{
				return this.GetAttributeValue<string>("county");
			}
			set
			{
				this.OnPropertyChanging("County");
				this.SetAttributeValue("county", value);
				this.OnPropertyChanged("County");
			}
		}
		
		/// <summary>
		/// Indicates the user that created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Indicates the date and time the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Indicates the user that the record was created on behalf of.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// OOTB address Primary Key, used when associating addresses through the UI.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customeraddressid")]
		public System.Nullable<System.Guid> CustomerAddressId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("customeraddressid");
			}
			set
			{
				this.OnPropertyChanging("CustomerAddressId");
				this.SetAttributeValue("customeraddressid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("CustomerAddressId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customeraddressid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.CustomerAddressId = value;
			}
		}
		
		/// <summary>
		/// Shows the conversion rate of the record's currency. The exchange rate is used to convert all money fields in the record from the local currency to the system's default currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// OOTB "fax" field, not used on any forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fax")]
		public string Fax
		{
			get
			{
				return this.GetAttributeValue<string>("fax");
			}
			set
			{
				this.OnPropertyChanging("Fax");
				this.SetAttributeValue("fax", value);
				this.OnPropertyChanged("Fax");
			}
		}
		
		/// <summary>
		/// OOTB freight terms field. Not exposed on any forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freighttermscode")]
		public virtual customeraddress_freighttermscode? FreightTermsCode
		{
			get
			{
				return ((customeraddress_freighttermscode?)(EntityOptionSetEnum.GetEnum(this, "freighttermscode")));
			}
			set
			{
				this.OnPropertyChanging("FreightTermsCode");
				this.SetAttributeValue("freighttermscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("FreightTermsCode");
			}
		}
		
		/// <summary>
		/// Unique identifier of the data import or data migration that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// OOTB latitude field, not exposed on any forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("latitude")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("latitude");
			}
			set
			{
				this.OnPropertyChanging("Latitude");
				this.SetAttributeValue("latitude", value);
				this.OnPropertyChanged("Latitude");
			}
		}
		
		/// <summary>
		/// OOTB Address Line 1 field, can be populated as a result of data normalization from Application, contact creation from Application, or Canada Post API. Exposed on member-facing Manage Address pages.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("line1")]
		public string Line1
		{
			get
			{
				return this.GetAttributeValue<string>("line1");
			}
			set
			{
				this.OnPropertyChanging("Line1");
				this.SetAttributeValue("line1", value);
				this.OnPropertyChanged("Line1");
			}
		}
		
		/// <summary>
		/// OOTB Address Line 2 field, can be populated as a result of data normalization from Application, contact creation from Application, or Canada Post API. Exposed on member-facing Manage Address pages.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("line2")]
		public string Line2
		{
			get
			{
				return this.GetAttributeValue<string>("line2");
			}
			set
			{
				this.OnPropertyChanging("Line2");
				this.SetAttributeValue("line2", value);
				this.OnPropertyChanged("Line2");
			}
		}
		
		/// <summary>
		/// OOTB Address Line 3 field, exposed on CRM forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("line3")]
		public string Line3
		{
			get
			{
				return this.GetAttributeValue<string>("line3");
			}
			set
			{
				this.OnPropertyChanging("Line3");
				this.SetAttributeValue("line3", value);
				this.OnPropertyChanged("Line3");
			}
		}
		
		/// <summary>
		/// OOTB longitude field, not exposed on any forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("longitude")]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("longitude");
			}
			set
			{
				this.OnPropertyChanging("Longitude");
				this.SetAttributeValue("longitude", value);
				this.OnPropertyChanged("Longitude");
			}
		}
		
		/// <summary>
		/// Indicates the last user to make changes to the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Indicates the date and time that the record was last updated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Indicates the last user that this record was modified on behalf of. Not exposed on any forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// OOTB address record name field, inherits the address type value. Set programmatically.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Autonumber unique address
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_address_id")]
		public string new_address_id
		{
			get
			{
				return this.GetAttributeValue<string>("new_address_id");
			}
			set
			{
				this.OnPropertyChanging("new_address_id");
				this.SetAttributeValue("new_address_id", value);
				this.OnPropertyChanged("new_address_id");
			}
		}
		
		/// <summary>
		/// Text data entry field to store additional contextual data for the address record. Data populated and maintained manually. Exposed on CRM forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_addressdescription")]
		public string new_AddressDescription
		{
			get
			{
				return this.GetAttributeValue<string>("new_addressdescription");
			}
			set
			{
				this.OnPropertyChanging("new_AddressDescription");
				this.SetAttributeValue("new_addressdescription", value);
				this.OnPropertyChanged("new_AddressDescription");
			}
		}
		
		/// <summary>
		/// Requires update any time address data changes. Exposed on CRM forms, populated programmatically when updates are made via portal. Used to track the source of the change to address data.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_addresssource")]
		public virtual new_addresssource? new_AddressSource
		{
			get
			{
				return ((new_addresssource?)(EntityOptionSetEnum.GetEnum(this, "new_addresssource")));
			}
			set
			{
				this.OnPropertyChanging("new_AddressSource");
				this.SetAttributeValue("new_addresssource", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_AddressSource");
			}
		}
		
		/// <summary>
		/// This field is populated with the new CMA Preferred Address in case user removes the previous CMA Preferred Address while engaging with member-facing manage address portal pages. Cleared afterwards.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_addresstypeforcmapreferredaddress")]
		public string new_AddressTypeForCMAPreferredAddress
		{
			get
			{
				return this.GetAttributeValue<string>("new_addresstypeforcmapreferredaddress");
			}
			set
			{
				this.OnPropertyChanging("new_AddressTypeForCMAPreferredAddress");
				this.SetAttributeValue("new_addresstypeforcmapreferredaddress", value);
				this.OnPropertyChanged("new_AddressTypeForCMAPreferredAddress");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_bulkprocesscomplete")]
		public System.Nullable<bool> new_BulkProcessComplete
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_bulkprocesscomplete");
			}
			set
			{
				this.OnPropertyChanging("new_BulkProcessComplete");
				this.SetAttributeValue("new_bulkprocesscomplete", value);
				this.OnPropertyChanged("new_BulkProcessComplete");
			}
		}
		
		/// <summary>
		/// Indicates the primary address for a contact. Referenced in multiple customizations (application data normalization/contact creation, opt address updates, etc.). Exposed on member-facing address pages.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cmapreferred")]
		public System.Nullable<bool> new_cmapreferred
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_cmapreferred");
			}
			set
			{
				this.OnPropertyChanging("new_cmapreferred");
				this.SetAttributeValue("new_cmapreferred", value);
				this.OnPropertyChanged("new_cmapreferred");
			}
		}
		
		/// <summary>
		/// Country field exposed in CRM and member-facing Manage Address pages. Populated manually and programmatically when address is created/updated from applications.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_country")]
		public virtual new_addresscountry? new_Country
		{
			get
			{
				return ((new_addresscountry?)(EntityOptionSetEnum.GetEnum(this, "new_country")));
			}
			set
			{
				this.OnPropertyChanging("new_Country");
				this.SetAttributeValue("new_country", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_Country");
			}
		}
		
		/// <summary>
		/// Read-only field exposed on CRM forms. Populated programmatically when postal code is updated - queries against table of electoral ridings in Azure to determine which to apply.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_electoraldiding")]
		public string new_electoraldiding
		{
			get
			{
				return this.GetAttributeValue<string>("new_electoraldiding");
			}
			set
			{
				this.OnPropertyChanging("new_electoraldiding");
				this.SetAttributeValue("new_electoraldiding", value);
				this.OnPropertyChanged("new_electoraldiding");
			}
		}
		
		/// <summary>
		/// Calculated field that pulls values from fields on the record to generate a concatenated address block. Not displayed on any form.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fulladdress")]
		public string new_FullAddress
		{
			get
			{
				return this.GetAttributeValue<string>("new_fulladdress");
			}
			set
			{
				this.OnPropertyChanging("new_FullAddress");
				this.SetAttributeValue("new_fulladdress", value);
				this.OnPropertyChanged("new_FullAddress");
			}
		}
		
		/// <summary>
		/// Indicates if an address has been verified as accurate. Data is set and managed manually, field exposed on CRM forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_isverified")]
		public System.Nullable<bool> new_IsVerified
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_isverified");
			}
			set
			{
				this.OnPropertyChanging("new_IsVerified");
				this.SetAttributeValue("new_isverified", value);
				this.OnPropertyChanged("new_IsVerified");
			}
		}
		
		/// <summary>
		/// CRM-only field used to track whether or not the CMA has received a mail bounce-back for the address in question. Referenced in custom logic that impacts the value in the Status field.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_returnmail")]
		public System.Nullable<bool> new_ReturnMail
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_returnmail");
			}
			set
			{
				this.OnPropertyChanging("new_ReturnMail");
				this.SetAttributeValue("new_returnmail", value);
				this.OnPropertyChanged("new_ReturnMail");
			}
		}
		
		/// <summary>
		/// Search bar used to query the Canada Post address database via API call. Exposed on CRM forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_search")]
		public string new_Search
		{
			get
			{
				return this.GetAttributeValue<string>("new_search");
			}
			set
			{
				this.OnPropertyChanging("new_Search");
				this.SetAttributeValue("new_search", value);
				this.OnPropertyChanged("new_Search");
			}
		}
		
		/// <summary>
		/// Field to support member-facing manage address functionality. Captures and displays list of Canadian provinces when a portal user indicates the country of the address is "Canada"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_stateorprovince_100000038")]
		public virtual new_addressstateorprovince_100000038? new_StateorProvince_100000038
		{
			get
			{
				return ((new_addressstateorprovince_100000038?)(EntityOptionSetEnum.GetEnum(this, "new_stateorprovince_100000038")));
			}
			set
			{
				this.OnPropertyChanging("new_StateorProvince_100000038");
				this.SetAttributeValue("new_stateorprovince_100000038", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_StateorProvince_100000038");
			}
		}
		
		/// <summary>
		/// Field to support member-facing manage address functionality. Captures and displays list of Canadian provinces when a portal user indicates the country of the address is "United States"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_stateorprovince_100000232")]
		public virtual new_addressstateorprovince_100000232? new_stateorprovince_100000232
		{
			get
			{
				return ((new_addressstateorprovince_100000232?)(EntityOptionSetEnum.GetEnum(this, "new_stateorprovince_100000232")));
			}
			set
			{
				this.OnPropertyChanging("new_stateorprovince_100000232");
				this.SetAttributeValue("new_stateorprovince_100000232", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_stateorprovince_100000232");
			}
		}
		
		/// <summary>
		/// Displays province/state master list. Exposed on CRM forms, populated both programmatically (application data normalization/contact create) and manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_stateorprovincemasterlist")]
		public virtual new_addressstateofprovince? new_StateorProvinceMasterList
		{
			get
			{
				return ((new_addressstateofprovince?)(EntityOptionSetEnum.GetEnum(this, "new_stateorprovincemasterlist")));
			}
			set
			{
				this.OnPropertyChanging("new_StateorProvinceMasterList");
				this.SetAttributeValue("new_stateorprovincemasterlist", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_StateorProvinceMasterList");
			}
		}
		
		/// <summary>
		/// Indicates whether an address is active or not. Referenced in custom logic tied to Return to sender field. Dependencies exist with portal components/view filtering (address management)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_status")]
		public System.Nullable<bool> new_Status
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_status");
			}
			set
			{
				this.OnPropertyChanging("new_Status");
				this.SetAttributeValue("new_status", value);
				this.OnPropertyChanged("new_Status");
			}
		}
		
		/// <summary>
		/// Shows the type code of the customer record to indicate whether the address belongs to a customer account or contact.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objecttypecode")]
		public string ObjectTypeCode
		{
			get
			{
				return this.GetAttributeValue<string>("objecttypecode");
			}
			set
			{
				this.OnPropertyChanging("ObjectTypeCode");
				this.SetAttributeValue("objecttypecode", value);
				this.OnPropertyChanged("ObjectTypeCode");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// CRM user that owns the individual Address record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Shows the business unit that the record owner belongs to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who owns the customer address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Choose the customer's address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentid")]
		public Microsoft.Xrm.Sdk.EntityReference ParentId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentid");
			}
			set
			{
				this.OnPropertyChanging("ParentId");
				this.SetAttributeValue("parentid", value);
				this.OnPropertyChanged("ParentId");
			}
		}
		
		/// <summary>
		/// OOTB Postal and Zip code field. Populated manually and programmatically (application data normalization/contact create). Exposed on member-facing address management pages.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("postalcode")]
		public string PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("postalcode");
			}
			set
			{
				this.OnPropertyChanging("PostalCode");
				this.SetAttributeValue("postalcode", value);
				this.OnPropertyChanged("PostalCode");
			}
		}
		
		/// <summary>
		/// OOTB post office box field, not exposed on forms. Referenced in customization that populates Address 1 with CMA preferred address data.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("postofficebox")]
		public string PostOfficeBox
		{
			get
			{
				return this.GetAttributeValue<string>("postofficebox");
			}
			set
			{
				this.OnPropertyChanging("PostOfficeBox");
				this.SetAttributeValue("postofficebox", value);
				this.OnPropertyChanged("PostOfficeBox");
			}
		}
		
		/// <summary>
		/// OOTB text field to store contact's name for the address record. Not used as part of current process, not exposed on any forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primarycontactname")]
		public string PrimaryContactName
		{
			get
			{
				return this.GetAttributeValue<string>("primarycontactname");
			}
			set
			{
				this.OnPropertyChanging("PrimaryContactName");
				this.SetAttributeValue("primarycontactname", value);
				this.OnPropertyChanged("PrimaryContactName");
			}
		}
		
		/// <summary>
		/// OOTB field used to track shipping method for the address record. Not used as part of current process, not exposed on forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shippingmethodcode")]
		public virtual customeraddress_shippingmethodcode? ShippingMethodCode
		{
			get
			{
				return ((customeraddress_shippingmethodcode?)(EntityOptionSetEnum.GetEnum(this, "shippingmethodcode")));
			}
			set
			{
				this.OnPropertyChanging("ShippingMethodCode");
				this.SetAttributeValue("shippingmethodcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ShippingMethodCode");
			}
		}
		
		/// <summary>
		/// OOTB state/province field. Not exposed on forms/used in current process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stateorprovince")]
		public string StateOrProvince
		{
			get
			{
				return this.GetAttributeValue<string>("stateorprovince");
			}
			set
			{
				this.OnPropertyChanging("StateOrProvince");
				this.SetAttributeValue("stateorprovince", value);
				this.OnPropertyChanged("StateOrProvince");
			}
		}
		
		/// <summary>
		/// OOTB field, not used or displayed on forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("telephone1")]
		public string Telephone1
		{
			get
			{
				return this.GetAttributeValue<string>("telephone1");
			}
			set
			{
				this.OnPropertyChanging("Telephone1");
				this.SetAttributeValue("telephone1", value);
				this.OnPropertyChanged("Telephone1");
			}
		}
		
		/// <summary>
		/// OOTB field, not used or displayed on forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("telephone2")]
		public string Telephone2
		{
			get
			{
				return this.GetAttributeValue<string>("telephone2");
			}
			set
			{
				this.OnPropertyChanging("Telephone2");
				this.SetAttributeValue("telephone2", value);
				this.OnPropertyChanged("Telephone2");
			}
		}
		
		/// <summary>
		/// OOTB field, not used or displayed on forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("telephone3")]
		public string Telephone3
		{
			get
			{
				return this.GetAttributeValue<string>("telephone3");
			}
			set
			{
				this.OnPropertyChanging("Telephone3");
				this.SetAttributeValue("telephone3", value);
				this.OnPropertyChanged("Telephone3");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Choose the local currency for the record to make sure budgets are reported in the correct currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// OOTB UPS Zone field, not used on any forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("upszone")]
		public string UPSZone
		{
			get
			{
				return this.GetAttributeValue<string>("upszone");
			}
			set
			{
				this.OnPropertyChanging("UPSZone");
				this.SetAttributeValue("upszone", value);
				this.OnPropertyChanged("UPSZone");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// OOTB UTC Offset field, unused in address functionality. Not used on any forms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcoffset")]
		public System.Nullable<int> UTCOffset
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcoffset");
			}
			set
			{
				this.OnPropertyChanging("UTCOffset");
				this.SetAttributeValue("utcoffset", value);
				this.OnPropertyChanged("UTCOffset");
			}
		}
		
		/// <summary>
		/// Version number of the customer address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 Account_CustomerAddress
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Account_CustomerAddress")]
		public CMA.Extensions.Model.Account Account_CustomerAddress
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Account>("Account_CustomerAddress", null);
			}
			set
			{
				this.OnPropertyChanging("Account_CustomerAddress");
				this.SetRelatedEntity<CMA.Extensions.Model.Account>("Account_CustomerAddress", null, value);
				this.OnPropertyChanged("Account_CustomerAddress");
			}
		}
		
		/// <summary>
		/// N:1 Contact_CustomerAddress
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Contact_CustomerAddress")]
		public CMA.Extensions.Model.Contact Contact_CustomerAddress
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Contact>("Contact_CustomerAddress", null);
			}
			set
			{
				this.OnPropertyChanging("Contact_CustomerAddress");
				this.SetRelatedEntity<CMA.Extensions.Model.Contact>("Contact_CustomerAddress", null, value);
				this.OnPropertyChanged("Contact_CustomerAddress");
			}
		}
		
		/// <summary>
		/// N:1 lk_customeraddress_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_customeraddress_createdonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_customeraddress_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_customeraddress_createdonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_customeraddress_createdonbehalfby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_customeraddress_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_customeraddress_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_customeraddress_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_customeraddress_modifiedonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_customeraddress_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_customeraddress_modifiedonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_customeraddress_modifiedonbehalfby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_customeraddress_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_customeraddress_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_customeraddressbase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_customeraddressbase_createdby")]
		public CMA.Extensions.Model.SystemUser lk_customeraddressbase_createdby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_customeraddressbase_createdby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_customeraddressbase_createdby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_customeraddressbase_createdby", null, value);
				this.OnPropertyChanged("lk_customeraddressbase_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_customeraddressbase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_customeraddressbase_modifiedby")]
		public CMA.Extensions.Model.SystemUser lk_customeraddressbase_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_customeraddressbase_modifiedby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_customeraddressbase_modifiedby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_customeraddressbase_modifiedby", null, value);
				this.OnPropertyChanged("lk_customeraddressbase_modifiedby");
			}
		}
	}
}
#pragma warning restore CS1591
