#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Status of the Event
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_event_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Event
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_event_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 100000005,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_event")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class new_event : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public new_event() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_event";
		
		public const string EntityLogicalCollectionName = "new_events";
		
		public const string EntitySetName = "new_events";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Indicates the user that created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Indicates the date and time the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Indicates the user on behalf of whom the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Indicates the user that modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Indicates the date and time the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Indicates the user on behalf of whom the record was updated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// No longer used as part of current process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_available")]
		public System.Nullable<int> new_available
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_available");
			}
			set
			{
				this.OnPropertyChanging("new_available");
				this.SetAttributeValue("new_available", value);
				this.OnPropertyChanged("new_available");
			}
		}
		
		/// <summary>
		/// Background field, used as reference to corresponding event record in Aventri. Set programmatically.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_aventrieventid")]
		public string new_aventrieventid
		{
			get
			{
				return this.GetAttributeValue<string>("new_aventrieventid");
			}
			set
			{
				this.OnPropertyChanging("new_aventrieventid");
				this.SetAttributeValue("new_aventrieventid", value);
				this.OnPropertyChanged("new_aventrieventid");
			}
		}
		
		/// <summary>
		/// Unique identifier for Product associated with Event.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cancelationproductid")]
		public Microsoft.Xrm.Sdk.EntityReference new_cancelationproductId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_cancelationproductid");
			}
			set
			{
				this.OnPropertyChanging("new_cancelationproductId");
				this.SetAttributeValue("new_cancelationproductid", value);
				this.OnPropertyChanged("new_cancelationproductId");
			}
		}
		
		/// <summary>
		/// Lookup field to link event record to a committee (type of account). Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_committeeaccountid")]
		public Microsoft.Xrm.Sdk.EntityReference new_CommitteeAccountID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_committeeaccountid");
			}
			set
			{
				this.OnPropertyChanging("new_CommitteeAccountID");
				this.SetAttributeValue("new_committeeaccountid", value);
				this.OnPropertyChanged("new_CommitteeAccountID");
			}
		}
		
		/// <summary>
		/// Acronym or shortened event name used internally. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_commonname")]
		public string new_CommonName
		{
			get
			{
				return this.GetAttributeValue<string>("new_commonname");
			}
			set
			{
				this.OnPropertyChanging("new_CommonName");
				this.SetAttributeValue("new_commonname", value);
				this.OnPropertyChanged("new_CommonName");
			}
		}
		
		/// <summary>
		/// Indicates the status of the contract with the event venue. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contractstatus")]
		public virtual new_eventcontractstatus? new_ContractStatus
		{
			get
			{
				return ((new_eventcontractstatus?)(EntityOptionSetEnum.GetEnum(this, "new_contractstatus")));
			}
			set
			{
				this.OnPropertyChanging("new_ContractStatus");
				this.SetAttributeValue("new_contractstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_ContractStatus");
			}
		}
		
		/// <summary>
		/// Background field, set programmatically.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_copyeventstatus")]
		public string new_CopyEventStatus
		{
			get
			{
				return this.GetAttributeValue<string>("new_copyeventstatus");
			}
			set
			{
				this.OnPropertyChanging("new_CopyEventStatus");
				this.SetAttributeValue("new_copyeventstatus", value);
				this.OnPropertyChanged("new_CopyEventStatus");
			}
		}
		
		/// <summary>
		/// Open text field for additional details about the event. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_description")]
		public string new_Description
		{
			get
			{
				return this.GetAttributeValue<string>("new_description");
			}
			set
			{
				this.OnPropertyChanging("new_Description");
				this.SetAttributeValue("new_description", value);
				this.OnPropertyChanged("new_Description");
			}
		}
		
		/// <summary>
		/// Review required - not used in current process. Historical data indicates use as a place to store content that would be sent to attendees once they confirm their attendance, possible email template.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_enconfirmationcontent")]
		public string new_ENConfirmationContent
		{
			get
			{
				return this.GetAttributeValue<string>("new_enconfirmationcontent");
			}
			set
			{
				this.OnPropertyChanging("new_ENConfirmationContent");
				this.SetAttributeValue("new_enconfirmationcontent", value);
				this.OnPropertyChanged("new_ENConfirmationContent");
			}
		}
		
		/// <summary>
		/// Indicates the date and time the event ends.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_enddate")]
		public System.Nullable<System.DateTime> new_EndDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_enddate");
			}
			set
			{
				this.OnPropertyChanging("new_EndDate");
				this.SetAttributeValue("new_enddate", value);
				this.OnPropertyChanged("new_EndDate");
			}
		}
		
		/// <summary>
		/// Unique numeric ID for the event record, set programmatically upon record creation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_event_id")]
		public string new_Event_Id
		{
			get
			{
				return this.GetAttributeValue<string>("new_event_id");
			}
			set
			{
				this.OnPropertyChanging("new_Event_Id");
				this.SetAttributeValue("new_event_id", value);
				this.OnPropertyChanged("new_Event_Id");
			}
		}
		
		/// <summary>
		/// Primary Key
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eventid")]
		public System.Nullable<System.Guid> new_eventId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_eventid");
			}
			set
			{
				this.OnPropertyChanging("new_eventId");
				this.SetAttributeValue("new_eventid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_eventId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eventid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.new_eventId = value;
			}
		}
		
		/// <summary>
		/// Indicates the sub-type of the event. List filtered based on selection in Event Type field and is referred to in that custom logic. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eventsubtypeid")]
		public Microsoft.Xrm.Sdk.EntityReference new_eventsubtypeid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_eventsubtypeid");
			}
			set
			{
				this.OnPropertyChanging("new_eventsubtypeid");
				this.SetAttributeValue("new_eventsubtypeid", value);
				this.OnPropertyChanged("new_eventsubtypeid");
			}
		}
		
		/// <summary>
		/// Indicates the category of the event. Selected value determines available sub-types.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eventtypeid")]
		public Microsoft.Xrm.Sdk.EntityReference new_eventtypeid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_eventtypeid");
			}
			set
			{
				this.OnPropertyChanging("new_eventtypeid");
				this.SetAttributeValue("new_eventtypeid", value);
				this.OnPropertyChanged("new_eventtypeid");
			}
		}
		
		/// <summary>
		/// Lookup field to the account record that represents the organization of the External Client for the event. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_externalclientaccountid")]
		public Microsoft.Xrm.Sdk.EntityReference new_ExternalClientAccountID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_externalclientaccountid");
			}
			set
			{
				this.OnPropertyChanging("new_ExternalClientAccountID");
				this.SetAttributeValue("new_externalclientaccountid", value);
				this.OnPropertyChanged("new_ExternalClientAccountID");
			}
		}
		
		/// <summary>
		/// Link to the contact record representing the point of contact for the External Client for an event. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_externalclientcontactid")]
		public Microsoft.Xrm.Sdk.EntityReference new_ExternalClientContactID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_externalclientcontactid");
			}
			set
			{
				this.OnPropertyChanging("new_ExternalClientContactID");
				this.SetAttributeValue("new_externalclientcontactid", value);
				this.OnPropertyChanged("new_ExternalClientContactID");
			}
		}
		
		/// <summary>
		/// No longer used as part of current process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_finalattendees")]
		public System.Nullable<int> new_finalattendees
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_finalattendees");
			}
			set
			{
				this.OnPropertyChanging("new_finalattendees");
				this.SetAttributeValue("new_finalattendees", value);
				this.OnPropertyChanged("new_finalattendees");
			}
		}
		
		/// <summary>
		/// Last Updated time of rollup field (Deprecated) Final Attendees.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_finalattendees_date")]
		public System.Nullable<System.DateTime> new_finalattendees_Date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_finalattendees_date");
			}
		}
		
		/// <summary>
		/// State of rollup field (Deprecated) Final Attendees.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_finalattendees_state")]
		public System.Nullable<int> new_finalattendees_State
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_finalattendees_state");
			}
		}
		
		/// <summary>
		/// Review required - not used in current process. Historical data indicates use as a place to store content that would be sent to attendees once they confirm their attendance, possible email template.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_frconfirmationcontent")]
		public string new_FRConfirmationContent
		{
			get
			{
				return this.GetAttributeValue<string>("new_frconfirmationcontent");
			}
			set
			{
				this.OnPropertyChanging("new_FRConfirmationContent");
				this.SetAttributeValue("new_frconfirmationcontent", value);
				this.OnPropertyChanged("new_FRConfirmationContent");
			}
		}
		
		/// <summary>
		/// Indicates which internal CMA business units that is the client for the event. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_internalclient")]
		public virtual new_eventinternalclient? new_InternalClient
		{
			get
			{
				return ((new_eventinternalclient?)(EntityOptionSetEnum.GetEnum(this, "new_internalclient")));
			}
			set
			{
				this.OnPropertyChanging("new_InternalClient");
				this.SetAttributeValue("new_internalclient", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_InternalClient");
			}
		}
		
		/// <summary>
		/// Lookup field to the contact record that represents the person who is the point of contact for the internal client of the event. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_internalclientcontact")]
		public string new_InternalClientContact
		{
			get
			{
				return this.GetAttributeValue<string>("new_internalclientcontact");
			}
			set
			{
				this.OnPropertyChanging("new_InternalClientContact");
				this.SetAttributeValue("new_internalclientcontact", value);
				this.OnPropertyChanged("new_InternalClientContact");
			}
		}
		
		/// <summary>
		/// Indicates the region in which the event is being held, for tax purposes. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_jurisdiction")]
		public virtual new_taxjurisdiction? new_Jurisdiction
		{
			get
			{
				return ((new_taxjurisdiction?)(EntityOptionSetEnum.GetEnum(this, "new_jurisdiction")));
			}
			set
			{
				this.OnPropertyChanging("new_Jurisdiction");
				this.SetAttributeValue("new_jurisdiction", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_Jurisdiction");
			}
		}
		
		/// <summary>
		/// Text field indicating the location of the primary venue. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_location")]
		public string new_Location
		{
			get
			{
				return this.GetAttributeValue<string>("new_location");
			}
			set
			{
				this.OnPropertyChanging("new_Location");
				this.SetAttributeValue("new_location", value);
				this.OnPropertyChanged("new_Location");
			}
		}
		
		/// <summary>
		/// Candidate for deletion - not used in current process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_lock")]
		public string new_Lock
		{
			get
			{
				return this.GetAttributeValue<string>("new_lock");
			}
			set
			{
				this.OnPropertyChanging("new_Lock");
				this.SetAttributeValue("new_lock", value);
				this.OnPropertyChanged("new_Lock");
			}
		}
		
		/// <summary>
		/// Candidate for deletion - not used in current process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_marketoprogramid")]
		public string new_MarketoProgramID
		{
			get
			{
				return this.GetAttributeValue<string>("new_marketoprogramid");
			}
			set
			{
				this.OnPropertyChanging("new_MarketoProgramID");
				this.SetAttributeValue("new_marketoprogramid", value);
				this.OnPropertyChanged("new_MarketoProgramID");
			}
		}
		
		/// <summary>
		/// Indicates the maximum number of attendees that can possibly be accommodated by the event / venue. Set manually, but plays a role in other calculations for capacity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_maximumattendees")]
		public System.Nullable<int> new_MaximumAttendees
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_maximumattendees");
			}
			set
			{
				this.OnPropertyChanging("new_MaximumAttendees");
				this.SetAttributeValue("new_maximumattendees", value);
				this.OnPropertyChanged("new_MaximumAttendees");
			}
		}
		
		/// <summary>
		/// Indicates the minimum number of attendees that need to attend in order to hold the event. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_minimumattendees")]
		public System.Nullable<int> new_MinimumAttendees
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_minimumattendees");
			}
			set
			{
				this.OnPropertyChanging("new_MinimumAttendees");
				this.SetAttributeValue("new_minimumattendees", value);
				this.OnPropertyChanged("new_MinimumAttendees");
			}
		}
		
		/// <summary>
		/// Indicates the date and time at which attendees and event staff move into a venue. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_moveindate")]
		public System.Nullable<System.DateTime> new_MoveInDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_moveindate");
			}
			set
			{
				this.OnPropertyChanging("new_MoveInDate");
				this.SetAttributeValue("new_moveindate", value);
				this.OnPropertyChanged("new_MoveInDate");
			}
		}
		
		/// <summary>
		/// Indicates the date and time at which attendees and event staff move out of a venue. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_moveoutdate")]
		public System.Nullable<System.DateTime> new_MoveOutDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_moveoutdate");
			}
			set
			{
				this.OnPropertyChanging("new_MoveOutDate");
				this.SetAttributeValue("new_moveoutdate", value);
				this.OnPropertyChanged("new_MoveOutDate");
			}
		}
		
		/// <summary>
		/// Name of the event. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
		public string new_name
		{
			get
			{
				return this.GetAttributeValue<string>("new_name");
			}
			set
			{
				this.OnPropertyChanging("new_name");
				this.SetAttributeValue("new_name", value);
				this.OnPropertyChanged("new_name");
			}
		}
		
		/// <summary>
		/// No longer used as part of current process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_noshows")]
		public System.Nullable<int> new_noshows
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_noshows");
			}
			set
			{
				this.OnPropertyChanging("new_noshows");
				this.SetAttributeValue("new_noshows", value);
				this.OnPropertyChanged("new_noshows");
			}
		}
		
		/// <summary>
		/// Last Updated time of rollup field (Deprecated) No-Shows.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_noshows_date")]
		public System.Nullable<System.DateTime> new_noshows_Date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_noshows_date");
			}
		}
		
		/// <summary>
		/// State of rollup field (Deprecated) No-Shows.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_noshows_state")]
		public System.Nullable<int> new_noshows_State
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_noshows_state");
			}
		}
		
		/// <summary>
		/// Indicates the targeted number of registrations for an event, knowing that some registrations might end up as no-shows. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_overbookingtarget")]
		public System.Nullable<int> new_overbookingtarget
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_overbookingtarget");
			}
			set
			{
				this.OnPropertyChanging("new_overbookingtarget");
				this.SetAttributeValue("new_overbookingtarget", value);
				this.OnPropertyChanged("new_overbookingtarget");
			}
		}
		
		/// <summary>
		/// Indicates which event to which the current event record is a sub-event (i.e. conferences and their separate sessions). Set manually or programmatically when creating sub events.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_parenteventid")]
		public Microsoft.Xrm.Sdk.EntityReference new_ParentEventID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_parenteventid");
			}
			set
			{
				this.OnPropertyChanging("new_ParentEventID");
				this.SetAttributeValue("new_parenteventid", value);
				this.OnPropertyChanged("new_ParentEventID");
			}
		}
		
		/// <summary>
		/// Indicates the primary venue (stored as an Account record in CRM) for the event. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_primaryvenueaccountid")]
		public Microsoft.Xrm.Sdk.EntityReference new_PrimaryVenueAccountID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_primaryvenueaccountid");
			}
			set
			{
				this.OnPropertyChanging("new_PrimaryVenueAccountID");
				this.SetAttributeValue("new_primaryvenueaccountid", value);
				this.OnPropertyChanged("new_PrimaryVenueAccountID");
			}
		}
		
		/// <summary>
		/// Unique identifier for Product associated with Event.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_productid")]
		public Microsoft.Xrm.Sdk.EntityReference new_productid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_productid");
			}
			set
			{
				this.OnPropertyChanging("new_productid");
				this.SetAttributeValue("new_productid", value);
				this.OnPropertyChanged("new_productid");
			}
		}
		
		/// <summary>
		/// No longer used as part of current process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_registered")]
		public System.Nullable<int> new_registered
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_registered");
			}
			set
			{
				this.OnPropertyChanging("new_registered");
				this.SetAttributeValue("new_registered", value);
				this.OnPropertyChanged("new_registered");
			}
		}
		
		/// <summary>
		/// Last Updated time of rollup field (Deprecated) Registered.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_registered_date")]
		public System.Nullable<System.DateTime> new_registered_Date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_registered_date");
			}
		}
		
		/// <summary>
		/// State of rollup field (Deprecated) Registered.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_registered_state")]
		public System.Nullable<int> new_registered_State
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_registered_state");
			}
		}
		
		/// <summary>
		/// Indicates the number of registered attendees associated to an event. Set programmatically by custom logic.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_registeredattendees")]
		public System.Nullable<int> new_registeredattendees
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_registeredattendees");
			}
			set
			{
				this.OnPropertyChanging("new_registeredattendees");
				this.SetAttributeValue("new_registeredattendees", value);
				this.OnPropertyChanged("new_registeredattendees");
			}
		}
		
		/// <summary>
		/// Indicates in which room of the venue the event will take place. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_room")]
		public string new_Room
		{
			get
			{
				return this.GetAttributeValue<string>("new_room");
			}
			set
			{
				this.OnPropertyChanging("new_Room");
				this.SetAttributeValue("new_room", value);
				this.OnPropertyChanged("new_Room");
			}
		}
		
		/// <summary>
		/// Indicates the maximum room capacity (i.e. per fire code) for the room in which the event is being held. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_roomcapacity")]
		public System.Nullable<int> new_roomcapacity
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_roomcapacity");
			}
			set
			{
				this.OnPropertyChanging("new_roomcapacity");
				this.SetAttributeValue("new_roomcapacity", value);
				this.OnPropertyChanged("new_roomcapacity");
			}
		}
		
		/// <summary>
		/// Open text field for providing additional detail about the room at the venue where the event will be held. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_roomdescription")]
		public string new_RoomDescription
		{
			get
			{
				return this.GetAttributeValue<string>("new_roomdescription");
			}
			set
			{
				this.OnPropertyChanging("new_RoomDescription");
				this.SetAttributeValue("new_roomdescription", value);
				this.OnPropertyChanged("new_RoomDescription");
			}
		}
		
		/// <summary>
		/// Indicates the number of attendees that must register for the event in order for it to be held. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_rsvpminimum")]
		public System.Nullable<int> new_rsvpminimum
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_rsvpminimum");
			}
			set
			{
				this.OnPropertyChanging("new_rsvpminimum");
				this.SetAttributeValue("new_rsvpminimum", value);
				this.OnPropertyChanged("new_rsvpminimum");
			}
		}
		
		/// <summary>
		/// Indicates the ID of the corresponding SABA class record (in SABA) to support integrations between systems. Referred to in customizations that perform that function. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_sabaclassid")]
		public string new_sabaclassid
		{
			get
			{
				return this.GetAttributeValue<string>("new_sabaclassid");
			}
			set
			{
				this.OnPropertyChanging("new_sabaclassid");
				this.SetAttributeValue("new_sabaclassid", value);
				this.OnPropertyChanged("new_sabaclassid");
			}
		}
		
		/// <summary>
		/// Indicates the date and time the event begins.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_startdate")]
		public System.Nullable<System.DateTime> new_StartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_startdate");
			}
			set
			{
				this.OnPropertyChanging("new_StartDate");
				this.SetAttributeValue("new_startdate", value);
				this.OnPropertyChanged("new_StartDate");
			}
		}
		
		/// <summary>
		/// Indicates the status of the event. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_status")]
		public virtual new_eventstatus? new_Status
		{
			get
			{
				return ((new_eventstatus?)(EntityOptionSetEnum.GetEnum(this, "new_status")));
			}
			set
			{
				this.OnPropertyChanging("new_Status");
				this.SetAttributeValue("new_status", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_Status");
			}
		}
		
		/// <summary>
		/// Indicates the ideal number of attendees the event hopes to attract. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_targetattendees")]
		public System.Nullable<int> new_TargetAttendees
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_targetattendees");
			}
			set
			{
				this.OnPropertyChanging("new_TargetAttendees");
				this.SetAttributeValue("new_targetattendees", value);
				this.OnPropertyChanged("new_TargetAttendees");
			}
		}
		
		/// <summary>
		/// Indicates the number of remaining seats/spaces are available at the event. Set programmatically based on inputs in the Capacity Information section.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_totalfinalattendees")]
		public System.Nullable<int> new_totalfinalattendees
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_totalfinalattendees");
			}
			set
			{
				this.OnPropertyChanging("new_totalfinalattendees");
				this.SetAttributeValue("new_totalfinalattendees", value);
				this.OnPropertyChanged("new_totalfinalattendees");
			}
		}
		
		/// <summary>
		/// Indicates the total number of attendees who registered but did not attend the event. Set programmatically by custom logic that queries the associated attendee records.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_totalnoshows")]
		public System.Nullable<int> new_totalnoshows
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_totalnoshows");
			}
			set
			{
				this.OnPropertyChanging("new_totalnoshows");
				this.SetAttributeValue("new_totalnoshows", value);
				this.OnPropertyChanged("new_totalnoshows");
			}
		}
		
		/// <summary>
		/// Rollup field that indicates the sum total of associated Attendees who have registered. Referred to in custom logic. Set programmatically.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_totalregistered")]
		public System.Nullable<int> new_totalregistered
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_totalregistered");
			}
			set
			{
				this.OnPropertyChanging("new_totalregistered");
				this.SetAttributeValue("new_totalregistered", value);
				this.OnPropertyChanged("new_totalregistered");
			}
		}
		
		/// <summary>
		/// Calculated field that displays how many spaces/seats are still available for the event, taking into consideration the different inputs from the Capacity Information section. Set programmatically.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_totalspaceavailable")]
		public System.Nullable<int> new_totalspaceavailable
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_totalspaceavailable");
			}
			set
			{
				this.OnPropertyChanging("new_totalspaceavailable");
				this.SetAttributeValue("new_totalspaceavailable", value);
				this.OnPropertyChanged("new_totalspaceavailable");
			}
		}
		
		/// <summary>
		/// Rollup field that indicates the number of associated events where the "Parent Event" field is set as the current event. Set programmatically.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_totalsubevents")]
		public System.Nullable<int> new_totalsubevents
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_totalsubevents");
			}
			set
			{
				this.OnPropertyChanging("new_totalsubevents");
				this.SetAttributeValue("new_totalsubevents", value);
				this.OnPropertyChanged("new_totalsubevents");
			}
		}
		
		/// <summary>
		/// Last Updated time of rollup field Sub-Events.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_totalsubevents_date")]
		public System.Nullable<System.DateTime> new_totalsubevents_Date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_totalsubevents_date");
			}
		}
		
		/// <summary>
		/// State of rollup field Sub-Events.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_totalsubevents_state")]
		public System.Nullable<int> new_totalsubevents_State
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("new_totalsubevents_state");
			}
		}
		
		/// <summary>
		/// Internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Indicates the owner of the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Default status for the custom entity, not used as part of current process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual new_event_statecode? statecode
		{
			get
			{
				return ((new_event_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Default state code field for the custom entity, not used as part of current process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_event_statuscode? statuscode
		{
			get
			{
				return ((new_event_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N new_event_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_Annotations")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Annotation> new_event_Annotations
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Annotation>("new_event_Annotations", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_Annotations");
				this.SetRelatedEntities<CMA.Extensions.Model.Annotation>("new_event_Annotations", null, value);
				this.OnPropertyChanged("new_event_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N new_event_campaign
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_campaign")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Campaign> new_event_campaign
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Campaign>("new_event_campaign", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_campaign");
				this.SetRelatedEntities<CMA.Extensions.Model.Campaign>("new_event_campaign", null, value);
				this.OnPropertyChanged("new_event_campaign");
			}
		}
		
		/// <summary>
		/// 1:N new_event_connections1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_connections1")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Connection> new_event_connections1
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Connection>("new_event_connections1", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_connections1");
				this.SetRelatedEntities<CMA.Extensions.Model.Connection>("new_event_connections1", null, value);
				this.OnPropertyChanged("new_event_connections1");
			}
		}
		
		/// <summary>
		/// 1:N new_event_connections2
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_connections2")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Connection> new_event_connections2
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Connection>("new_event_connections2", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_connections2");
				this.SetRelatedEntities<CMA.Extensions.Model.Connection>("new_event_connections2", null, value);
				this.OnPropertyChanged("new_event_connections2");
			}
		}
		
		/// <summary>
		/// 1:N new_event_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_Emails")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Email> new_event_Emails
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Email>("new_event_Emails", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_Emails");
				this.SetRelatedEntities<CMA.Extensions.Model.Email>("new_event_Emails", null, value);
				this.OnPropertyChanged("new_event_Emails");
			}
		}
		
		/// <summary>
		/// 1:N new_event_event
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_event", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_event> Referencednew_event_event
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_event>("new_event_event", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referencednew_event_event");
				this.SetRelatedEntities<CMA.Extensions.Model.new_event>("new_event_event", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencednew_event_event");
			}
		}
		
		/// <summary>
		/// 1:N new_event_Letters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_Letters")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Letter> new_event_Letters
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Letter>("new_event_Letters", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_Letters");
				this.SetRelatedEntities<CMA.Extensions.Model.Letter>("new_event_Letters", null, value);
				this.OnPropertyChanged("new_event_Letters");
			}
		}
		
		/// <summary>
		/// 1:N new_event_new_eventfollowups
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_new_eventfollowups")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_eventfollowup> new_event_new_eventfollowups
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_eventfollowup>("new_event_new_eventfollowups", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_new_eventfollowups");
				this.SetRelatedEntities<CMA.Extensions.Model.new_eventfollowup>("new_event_new_eventfollowups", null, value);
				this.OnPropertyChanged("new_event_new_eventfollowups");
			}
		}
		
		/// <summary>
		/// 1:N new_event_new_smses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_new_smses")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_sms> new_event_new_smses
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_sms>("new_event_new_smses", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_new_smses");
				this.SetRelatedEntities<CMA.Extensions.Model.new_sms>("new_event_new_smses", null, value);
				this.OnPropertyChanged("new_event_new_smses");
			}
		}
		
		/// <summary>
		/// 1:N new_event_new_submittedquestions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_new_submittedquestions")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_submittedquestion> new_event_new_submittedquestions
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_submittedquestion>("new_event_new_submittedquestions", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_new_submittedquestions");
				this.SetRelatedEntities<CMA.Extensions.Model.new_submittedquestion>("new_event_new_submittedquestions", null, value);
				this.OnPropertyChanged("new_event_new_submittedquestions");
			}
		}
		
		/// <summary>
		/// 1:N new_event_PhoneCalls
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_PhoneCalls")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.PhoneCall> new_event_PhoneCalls
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.PhoneCall>("new_event_PhoneCalls", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_PhoneCalls");
				this.SetRelatedEntities<CMA.Extensions.Model.PhoneCall>("new_event_PhoneCalls", null, value);
				this.OnPropertyChanged("new_event_PhoneCalls");
			}
		}
		
		/// <summary>
		/// 1:N new_event_productkit
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_productkit")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Product> new_event_productkit
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Product>("new_event_productkit", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_productkit");
				this.SetRelatedEntities<CMA.Extensions.Model.Product>("new_event_productkit", null, value);
				this.OnPropertyChanged("new_event_productkit");
			}
		}
		
		/// <summary>
		/// 1:N new_event_Tasks
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_Tasks")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Task> new_event_Tasks
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Task>("new_event_Tasks", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_Tasks");
				this.SetRelatedEntities<CMA.Extensions.Model.Task>("new_event_Tasks", null, value);
				this.OnPropertyChanged("new_event_Tasks");
			}
		}
		
		/// <summary>
		/// 1:N new_new_event_new_eventattendee
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_event_new_eventattendee")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_eventattendee> new_new_event_new_eventattendee
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_eventattendee>("new_new_event_new_eventattendee", null);
			}
			set
			{
				this.OnPropertyChanging("new_new_event_new_eventattendee");
				this.SetRelatedEntities<CMA.Extensions.Model.new_eventattendee>("new_new_event_new_eventattendee", null, value);
				this.OnPropertyChanged("new_new_event_new_eventattendee");
			}
		}
		
		/// <summary>
		/// 1:N new_new_event_opportunity_SourceEventId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_event_opportunity_SourceEventId")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Opportunity> new_new_event_opportunity_SourceEventId
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Opportunity>("new_new_event_opportunity_SourceEventId", null);
			}
			set
			{
				this.OnPropertyChanging("new_new_event_opportunity_SourceEventId");
				this.SetRelatedEntities<CMA.Extensions.Model.Opportunity>("new_new_event_opportunity_SourceEventId", null, value);
				this.OnPropertyChanged("new_new_event_opportunity_SourceEventId");
			}
		}
		
		/// <summary>
		/// N:N new_eventattendee_event
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_eventattendee_event")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_eventattendee> new_eventattendee_event
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_eventattendee>("new_eventattendee_event", null);
			}
			set
			{
				this.OnPropertyChanging("new_eventattendee_event");
				this.SetRelatedEntities<CMA.Extensions.Model.new_eventattendee>("new_eventattendee_event", null, value);
				this.OnPropertyChanged("new_eventattendee_event");
			}
		}
		
		/// <summary>
		/// N:N new_events_accountvenues
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_events_accountvenues")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Account> new_events_accountvenues
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Account>("new_events_accountvenues", null);
			}
			set
			{
				this.OnPropertyChanging("new_events_accountvenues");
				this.SetRelatedEntities<CMA.Extensions.Model.Account>("new_events_accountvenues", null, value);
				this.OnPropertyChanged("new_events_accountvenues");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_event_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_event_createdby")]
		public CMA.Extensions.Model.SystemUser lk_new_event_createdby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_event_createdby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_new_event_createdby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_event_createdby", null, value);
				this.OnPropertyChanged("lk_new_event_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_event_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_event_createdonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_event_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_event_createdonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_new_event_createdonbehalfby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_event_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_new_event_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_event_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_event_modifiedby")]
		public CMA.Extensions.Model.SystemUser lk_new_event_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_event_modifiedby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_new_event_modifiedby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_event_modifiedby", null, value);
				this.OnPropertyChanged("lk_new_event_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_event_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_event_modifiedonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_event_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_event_modifiedonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_new_event_modifiedonbehalfby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_event_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_new_event_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 new_account_event_Committee
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_committeeaccountid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_account_event_Committee")]
		public CMA.Extensions.Model.Account new_account_event_Committee
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Account>("new_account_event_Committee", null);
			}
			set
			{
				this.OnPropertyChanging("new_account_event_Committee");
				this.SetRelatedEntity<CMA.Extensions.Model.Account>("new_account_event_Committee", null, value);
				this.OnPropertyChanged("new_account_event_Committee");
			}
		}
		
		/// <summary>
		/// N:1 new_account_event_ExternalClient
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_externalclientaccountid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_account_event_ExternalClient")]
		public CMA.Extensions.Model.Account new_account_event_ExternalClient
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Account>("new_account_event_ExternalClient", null);
			}
			set
			{
				this.OnPropertyChanging("new_account_event_ExternalClient");
				this.SetRelatedEntity<CMA.Extensions.Model.Account>("new_account_event_ExternalClient", null, value);
				this.OnPropertyChanged("new_account_event_ExternalClient");
			}
		}
		
		/// <summary>
		/// N:1 new_account_event_Venue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_primaryvenueaccountid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_account_event_Venue")]
		public CMA.Extensions.Model.Account new_account_event_Venue
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Account>("new_account_event_Venue", null);
			}
			set
			{
				this.OnPropertyChanging("new_account_event_Venue");
				this.SetRelatedEntity<CMA.Extensions.Model.Account>("new_account_event_Venue", null, value);
				this.OnPropertyChanged("new_account_event_Venue");
			}
		}
		
		/// <summary>
		/// N:1 new_contact_event
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_externalclientcontactid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_contact_event")]
		public CMA.Extensions.Model.Contact new_contact_event
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Contact>("new_contact_event", null);
			}
			set
			{
				this.OnPropertyChanging("new_contact_event");
				this.SetRelatedEntity<CMA.Extensions.Model.Contact>("new_contact_event", null, value);
				this.OnPropertyChanged("new_contact_event");
			}
		}
		
		/// <summary>
		/// N:1 new_event_event
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_parenteventid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_event", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public CMA.Extensions.Model.new_event Referencingnew_event_event
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_event>("new_event_event", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.OnPropertyChanging("Referencingnew_event_event");
				this.SetRelatedEntity<CMA.Extensions.Model.new_event>("new_event_event", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingnew_event_event");
			}
		}
		
		/// <summary>
		/// N:1 new_event_eventsubtypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eventsubtypeid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_eventsubtypeid")]
		public CMA.Extensions.Model.new_eventtype new_event_eventsubtypeid
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_eventtype>("new_event_eventsubtypeid", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_eventsubtypeid");
				this.SetRelatedEntity<CMA.Extensions.Model.new_eventtype>("new_event_eventsubtypeid", null, value);
				this.OnPropertyChanged("new_event_eventsubtypeid");
			}
		}
		
		/// <summary>
		/// N:1 new_event_eventtypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eventtypeid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_eventtypeid")]
		public CMA.Extensions.Model.new_eventtype new_event_eventtypeid
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_eventtype>("new_event_eventtypeid", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_eventtypeid");
				this.SetRelatedEntity<CMA.Extensions.Model.new_eventtype>("new_event_eventtypeid", null, value);
				this.OnPropertyChanged("new_event_eventtypeid");
			}
		}
		
		/// <summary>
		/// N:1 new_product_event
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_productid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_product_event")]
		public CMA.Extensions.Model.Product new_product_event
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Product>("new_product_event", null);
			}
			set
			{
				this.OnPropertyChanging("new_product_event");
				this.SetRelatedEntity<CMA.Extensions.Model.Product>("new_product_event", null, value);
				this.OnPropertyChanged("new_product_event");
			}
		}
		
		/// <summary>
		/// N:1 new_product_event_cancelproductid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cancelationproductid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_product_event_cancelproductid")]
		public CMA.Extensions.Model.Product new_product_event_cancelproductid
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Product>("new_product_event_cancelproductid", null);
			}
			set
			{
				this.OnPropertyChanging("new_product_event_cancelproductid");
				this.SetRelatedEntity<CMA.Extensions.Model.Product>("new_product_event_cancelproductid", null, value);
				this.OnPropertyChanged("new_product_event_cancelproductid");
			}
		}
		
		/// <summary>
		/// N:1 user_new_event
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_new_event")]
		public CMA.Extensions.Model.SystemUser user_new_event
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("user_new_event", null);
			}
		}
	}
}
#pragma warning restore CS1591
