#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Status of the PSI / Emerging Issue
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_psi_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the PSI / Emerging Issue
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_psi_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_psi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class new_psi : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public new_psi() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_psi";
		
		public const string EntityLogicalCollectionName = "new_psis";
		
		public const string EntitySetName = "new_psis";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// The English Name of the PSI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_englishname")]
		public string new_EnglishName
		{
			get
			{
				return this.GetAttributeValue<string>("new_englishname");
			}
			set
			{
				this.OnPropertyChanging("new_EnglishName");
				this.SetAttributeValue("new_englishname", value);
				this.OnPropertyChanged("new_EnglishName");
			}
		}
		
		/// <summary>
		/// The French Name of the PSI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_frenchname")]
		public string new_FrenchName
		{
			get
			{
				return this.GetAttributeValue<string>("new_frenchname");
			}
			set
			{
				this.OnPropertyChanging("new_FrenchName");
				this.SetAttributeValue("new_frenchname", value);
				this.OnPropertyChanged("new_FrenchName");
			}
		}
		
		/// <summary>
		/// The name of the PSI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
		public string new_name
		{
			get
			{
				return this.GetAttributeValue<string>("new_name");
			}
			set
			{
				this.OnPropertyChanging("new_name");
				this.SetAttributeValue("new_name", value);
				this.OnPropertyChanged("new_name");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_psiid")]
		public System.Nullable<System.Guid> new_psiId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_psiid");
			}
			set
			{
				this.OnPropertyChanging("new_psiId");
				this.SetAttributeValue("new_psiid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_psiId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_psiid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.new_psiId = value;
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the PSI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual new_psi_statecode? statecode
		{
			get
			{
				return ((new_psi_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the PSI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_psi_statuscode? statuscode
		{
			get
			{
				return ((new_psi_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N new_psi_connections1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_psi_connections1")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Connection> new_psi_connections1
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Connection>("new_psi_connections1", null);
			}
			set
			{
				this.OnPropertyChanging("new_psi_connections1");
				this.SetRelatedEntities<CMA.Extensions.Model.Connection>("new_psi_connections1", null, value);
				this.OnPropertyChanged("new_psi_connections1");
			}
		}
		
		/// <summary>
		/// 1:N new_psi_connections2
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_psi_connections2")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Connection> new_psi_connections2
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Connection>("new_psi_connections2", null);
			}
			set
			{
				this.OnPropertyChanging("new_psi_connections2");
				this.SetRelatedEntities<CMA.Extensions.Model.Connection>("new_psi_connections2", null, value);
				this.OnPropertyChanged("new_psi_connections2");
			}
		}
		
		/// <summary>
		/// N:N new_account_psi
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_account_psi")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Account> new_account_psi
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Account>("new_account_psi", null);
			}
			set
			{
				this.OnPropertyChanging("new_account_psi");
				this.SetRelatedEntities<CMA.Extensions.Model.Account>("new_account_psi", null, value);
				this.OnPropertyChanged("new_account_psi");
			}
		}
		
		/// <summary>
		/// N:N new_contact_psi
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_contact_psi")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Contact> new_contact_psi
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Contact>("new_contact_psi", null);
			}
			set
			{
				this.OnPropertyChanging("new_contact_psi");
				this.SetRelatedEntities<CMA.Extensions.Model.Contact>("new_contact_psi", null, value);
				this.OnPropertyChanged("new_contact_psi");
			}
		}
		
		/// <summary>
		/// N:N new_opportunity_psi
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_opportunity_psi")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Opportunity> new_opportunity_psi
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Opportunity>("new_opportunity_psi", null);
			}
			set
			{
				this.OnPropertyChanging("new_opportunity_psi");
				this.SetRelatedEntities<CMA.Extensions.Model.Opportunity>("new_opportunity_psi", null, value);
				this.OnPropertyChanged("new_opportunity_psi");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_psi_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_psi_createdby")]
		public CMA.Extensions.Model.SystemUser lk_new_psi_createdby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_psi_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_psi_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_psi_createdonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_psi_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_psi_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_psi_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_psi_modifiedby")]
		public CMA.Extensions.Model.SystemUser lk_new_psi_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_psi_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_psi_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_psi_modifiedonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_psi_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_psi_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_new_psi
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_new_psi")]
		public CMA.Extensions.Model.SystemUser user_new_psi
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("user_new_psi", null);
			}
		}
	}
}
#pragma warning restore CS1591
