#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Status of the Event Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_eventtype_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Event Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_eventtype_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_eventtype")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class new_eventtype : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public new_eventtype() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_eventtype";
		
		public const string EntityLogicalCollectionName = "new_eventtypes";
		
		public const string EntitySetName = "new_eventtypes";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// English name, added to data model in case of future exposure on member-facing portal / adherence to custom design determined when creating Contact Type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_english")]
		public string new_english
		{
			get
			{
				return this.GetAttributeValue<string>("new_english");
			}
			set
			{
				this.OnPropertyChanging("new_english");
				this.SetAttributeValue("new_english", value);
				this.OnPropertyChanged("new_english");
			}
		}
		
		/// <summary>
		/// Unique autonumber value
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eventtype_id")]
		public string new_eventtype_id
		{
			get
			{
				return this.GetAttributeValue<string>("new_eventtype_id");
			}
			set
			{
				this.OnPropertyChanging("new_eventtype_id");
				this.SetAttributeValue("new_eventtype_id", value);
				this.OnPropertyChanged("new_eventtype_id");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eventtypeid")]
		public System.Nullable<System.Guid> new_eventtypeId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_eventtypeid");
			}
			set
			{
				this.OnPropertyChanging("new_eventtypeId");
				this.SetAttributeValue("new_eventtypeid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_eventtypeId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eventtypeid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.new_eventtypeId = value;
			}
		}
		
		/// <summary>
		/// French name, added to data model in case of future exposure on member-facing portal / adherence to custom design determined when creating Contact Type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_french")]
		public string new_french
		{
			get
			{
				return this.GetAttributeValue<string>("new_french");
			}
			set
			{
				this.OnPropertyChanging("new_french");
				this.SetAttributeValue("new_french", value);
				this.OnPropertyChanged("new_french");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
		public string new_name
		{
			get
			{
				return this.GetAttributeValue<string>("new_name");
			}
			set
			{
				this.OnPropertyChanging("new_name");
				this.SetAttributeValue("new_name", value);
				this.OnPropertyChanged("new_name");
			}
		}
		
		/// <summary>
		/// Lookup field that supports self-referential hierarchy of Event Types (allows sub-types to be linked to specific parent "Types"). Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_parenttypeid")]
		public Microsoft.Xrm.Sdk.EntityReference new_parenttypeid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_parenttypeid");
			}
			set
			{
				this.OnPropertyChanging("new_parenttypeid");
				this.SetAttributeValue("new_parenttypeid", value);
				this.OnPropertyChanged("new_parenttypeid");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Status of the Event Type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual new_eventtype_statecode? statecode
		{
			get
			{
				return ((new_eventtype_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Event Type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_eventtype_statuscode? statuscode
		{
			get
			{
				return ((new_eventtype_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N new_event_eventsubtypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_eventsubtypeid")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_event> new_event_eventsubtypeid
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_event>("new_event_eventsubtypeid", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_eventsubtypeid");
				this.SetRelatedEntities<CMA.Extensions.Model.new_event>("new_event_eventsubtypeid", null, value);
				this.OnPropertyChanged("new_event_eventsubtypeid");
			}
		}
		
		/// <summary>
		/// 1:N new_event_eventtypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_event_eventtypeid")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_event> new_event_eventtypeid
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_event>("new_event_eventtypeid", null);
			}
			set
			{
				this.OnPropertyChanging("new_event_eventtypeid");
				this.SetRelatedEntities<CMA.Extensions.Model.new_event>("new_event_eventtypeid", null, value);
				this.OnPropertyChanged("new_event_eventtypeid");
			}
		}
		
		/// <summary>
		/// 1:N new_eventtype_parenttypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_eventtype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_eventtype> Referencednew_eventtype_parenttypeid
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_eventtype>("new_eventtype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referencednew_eventtype_parenttypeid");
				this.SetRelatedEntities<CMA.Extensions.Model.new_eventtype>("new_eventtype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencednew_eventtype_parenttypeid");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_eventtype_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_eventtype_createdby")]
		public CMA.Extensions.Model.SystemUser lk_new_eventtype_createdby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_eventtype_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_eventtype_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_eventtype_createdonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_eventtype_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_eventtype_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_eventtype_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_eventtype_modifiedby")]
		public CMA.Extensions.Model.SystemUser lk_new_eventtype_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_eventtype_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_eventtype_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_eventtype_modifiedonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_eventtype_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_eventtype_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 new_eventtype_parenttypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_parenttypeid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_eventtype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public CMA.Extensions.Model.new_eventtype Referencingnew_eventtype_parenttypeid
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_eventtype>("new_eventtype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.OnPropertyChanging("Referencingnew_eventtype_parenttypeid");
				this.SetRelatedEntity<CMA.Extensions.Model.new_eventtype>("new_eventtype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingnew_eventtype_parenttypeid");
			}
		}
	}
}
#pragma warning restore CS1591
