#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_appealresult_new_grantsubmission
	{
		
		/// <summary>
		///  
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Accepted = 100000000,
		
		/// <summary>
		///  
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejected = 100000001,
	}
	
	/// <summary>
	/// Status of the Grant Submission
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_grantsubmission_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Grant Submission
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_grantsubmission_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_grantsubmission")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class new_grantsubmission : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public new_grantsubmission() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_grantsubmission";
		
		public const string EntityLogicalCollectionName = "new_grantsubmissions";
		
		public const string EntitySetName = "new_grantsubmissions";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Indicates whether or not the submitter accepted the terms and conditions of the grant program.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_acceptedterms")]
		public System.Nullable<bool> new_acceptedterms
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_acceptedterms");
			}
			set
			{
				this.OnPropertyChanging("new_acceptedterms");
				this.SetAttributeValue("new_acceptedterms", value);
				this.OnPropertyChanged("new_acceptedterms");
			}
		}
		
		/// <summary>
		/// Indicates the date on which submitter executed the agreement.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_agreementdate")]
		public System.Nullable<System.DateTime> new_agreementdate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_agreementdate");
			}
			set
			{
				this.OnPropertyChanging("new_agreementdate");
				this.SetAttributeValue("new_agreementdate", value);
				this.OnPropertyChanged("new_agreementdate");
			}
		}
		
		/// <summary>
		/// Indicates the date on which the appeal was made.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_appealdate")]
		public System.Nullable<System.DateTime> new_appealdate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_appealdate");
			}
			set
			{
				this.OnPropertyChanging("new_appealdate");
				this.SetAttributeValue("new_appealdate", value);
				this.OnPropertyChanged("new_appealdate");
			}
		}
		
		/// <summary>
		/// Indicates whether or not a grant submission was appealed by the submitter.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_appealed")]
		public System.Nullable<bool> new_appealed
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_appealed");
			}
			set
			{
				this.OnPropertyChanging("new_appealed");
				this.SetAttributeValue("new_appealed", value);
				this.OnPropertyChanged("new_appealed");
			}
		}
		
		/// <summary>
		/// Additional space to provide written context for the appeal.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_appealnotes")]
		public string new_appealnotes
		{
			get
			{
				return this.GetAttributeValue<string>("new_appealnotes");
			}
			set
			{
				this.OnPropertyChanging("new_appealnotes");
				this.SetAttributeValue("new_appealnotes", value);
				this.OnPropertyChanged("new_appealnotes");
			}
		}
		
		/// <summary>
		/// Indicates whether the appeal was accepted or rejected by the grant program organizers.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_appealresult")]
		public virtual new_appealresult_new_grantsubmission? new_appealresult
		{
			get
			{
				return ((new_appealresult_new_grantsubmission?)(EntityOptionSetEnum.GetEnum(this, "new_appealresult")));
			}
			set
			{
				this.OnPropertyChanging("new_appealresult");
				this.SetAttributeValue("new_appealresult", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_appealresult");
			}
		}
		
		/// <summary>
		/// Open text field for additional notes about the grant submission.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_closingcomments")]
		public string new_closingcomments
		{
			get
			{
				return this.GetAttributeValue<string>("new_closingcomments");
			}
			set
			{
				this.OnPropertyChanging("new_closingcomments");
				this.SetAttributeValue("new_closingcomments", value);
				this.OnPropertyChanged("new_closingcomments");
			}
		}
		
		/// <summary>
		/// Indicates whether or not the agreement was executed.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_executedagreement")]
		public System.Nullable<bool> new_executedagreement
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_executedagreement");
			}
			set
			{
				this.OnPropertyChanging("new_executedagreement");
				this.SetAttributeValue("new_executedagreement", value);
				this.OnPropertyChanged("new_executedagreement");
			}
		}
		
		/// <summary>
		/// Indicates the dollar amount that is being requested in the grant submission.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_grantamount")]
		public Microsoft.Xrm.Sdk.Money new_grantamount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_grantamount");
			}
			set
			{
				this.OnPropertyChanging("new_grantamount");
				this.SetAttributeValue("new_grantamount", value);
				this.OnPropertyChanged("new_grantamount");
			}
		}
		
		/// <summary>
		/// Value of the Grant Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_grantamount_base")]
		public Microsoft.Xrm.Sdk.Money new_grantamount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_grantamount_base");
			}
		}
		
		/// <summary>
		/// Lookup to Grant Program for which the Grant Submission has been submitted.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_grantprogramid")]
		public Microsoft.Xrm.Sdk.EntityReference new_grantprogramid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_grantprogramid");
			}
			set
			{
				this.OnPropertyChanging("new_grantprogramid");
				this.SetAttributeValue("new_grantprogramid", value);
				this.OnPropertyChanged("new_grantprogramid");
			}
		}
		
		/// <summary>
		/// Set programmatically when record is created, can be modified manually. Sequential numeric string assigned to grant submissions when created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_grantsubmission_id")]
		public string new_grantsubmission_id
		{
			get
			{
				return this.GetAttributeValue<string>("new_grantsubmission_id");
			}
			set
			{
				this.OnPropertyChanging("new_grantsubmission_id");
				this.SetAttributeValue("new_grantsubmission_id", value);
				this.OnPropertyChanged("new_grantsubmission_id");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_grantsubmissionid")]
		public System.Nullable<System.Guid> new_grantsubmissionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_grantsubmissionid");
			}
			set
			{
				this.OnPropertyChanging("new_grantsubmissionId");
				this.SetAttributeValue("new_grantsubmissionid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_grantsubmissionId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_grantsubmissionid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.new_grantsubmissionId = value;
			}
		}
		
		/// <summary>
		/// Name of the initiative for which the submitter seeks funding as part of the grant program.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_initiativename")]
		public string new_initiativename
		{
			get
			{
				return this.GetAttributeValue<string>("new_initiativename");
			}
			set
			{
				this.OnPropertyChanging("new_initiativename");
				this.SetAttributeValue("new_initiativename", value);
				this.OnPropertyChanged("new_initiativename");
			}
		}
		
		/// <summary>
		/// Date at which the monitoring period for the submission ends.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_monitoringenddate")]
		public System.Nullable<System.DateTime> new_monitoringenddate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_monitoringenddate");
			}
			set
			{
				this.OnPropertyChanging("new_monitoringenddate");
				this.SetAttributeValue("new_monitoringenddate", value);
				this.OnPropertyChanged("new_monitoringenddate");
			}
		}
		
		/// <summary>
		/// Date on which the monitoring period for the submission begins.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_monitoringstartdate")]
		public System.Nullable<System.DateTime> new_monitoringstartdate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_monitoringstartdate");
			}
			set
			{
				this.OnPropertyChanging("new_monitoringstartdate");
				this.SetAttributeValue("new_monitoringstartdate", value);
				this.OnPropertyChanged("new_monitoringstartdate");
			}
		}
		
		/// <summary>
		/// Indicates whether or not the submitter received payment after successfully being granted funds.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentreceived")]
		public System.Nullable<bool> new_paymentreceived
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_paymentreceived");
			}
			set
			{
				this.OnPropertyChanging("new_paymentreceived");
				this.SetAttributeValue("new_paymentreceived", value);
				this.OnPropertyChanged("new_paymentreceived");
			}
		}
		
		/// <summary>
		/// Indicates the date on which the payment was received by the submitter. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentreceiveddate")]
		public System.Nullable<System.DateTime> new_paymentreceiveddate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_paymentreceiveddate");
			}
			set
			{
				this.OnPropertyChanging("new_paymentreceiveddate");
				this.SetAttributeValue("new_paymentreceiveddate", value);
				this.OnPropertyChanged("new_paymentreceiveddate");
			}
		}
		
		/// <summary>
		/// Status of the grant submission, indicates the point of the process at which submission is in. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_status")]
		public virtual new_grantsubmission_status? new_status
		{
			get
			{
				return ((new_grantsubmission_status?)(EntityOptionSetEnum.GetEnum(this, "new_status")));
			}
			set
			{
				this.OnPropertyChanging("new_status");
				this.SetAttributeValue("new_status", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_status");
			}
		}
		
		/// <summary>
		/// Indicates the date and time that the grant submission was submitted.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_submissiondate")]
		public System.Nullable<System.DateTime> new_submissiondate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_submissiondate");
			}
			set
			{
				this.OnPropertyChanging("new_submissiondate");
				this.SetAttributeValue("new_submissiondate", value);
				this.OnPropertyChanged("new_submissiondate");
			}
		}
		
		/// <summary>
		/// Open text field to contain a written summary of the initiative for which the submitter is seeking funding.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_submissiondescription")]
		public string new_submissiondescription
		{
			get
			{
				return this.GetAttributeValue<string>("new_submissiondescription");
			}
			set
			{
				this.OnPropertyChanging("new_submissiondescription");
				this.SetAttributeValue("new_submissiondescription", value);
				this.OnPropertyChanged("new_submissiondescription");
			}
		}
		
		/// <summary>
		/// URL link to relevant web pages related to the initiative being submitted or the submission itself.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_submissionlink")]
		public string new_submissionlink
		{
			get
			{
				return this.GetAttributeValue<string>("new_submissionlink");
			}
			set
			{
				this.OnPropertyChanging("new_submissionlink");
				this.SetAttributeValue("new_submissionlink", value);
				this.OnPropertyChanged("new_submissionlink");
			}
		}
		
		/// <summary>
		/// Text field that indicates the current stage the submission is at along the process, set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_submissionstage")]
		public string new_submissionstage
		{
			get
			{
				return this.GetAttributeValue<string>("new_submissionstage");
			}
			set
			{
				this.OnPropertyChanging("new_submissionstage");
				this.SetAttributeValue("new_submissionstage", value);
				this.OnPropertyChanged("new_submissionstage");
			}
		}
		
		/// <summary>
		/// Text field for capturing the type of grant submission.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_submissiontype")]
		public string new_submissiontype
		{
			get
			{
				return this.GetAttributeValue<string>("new_submissiontype");
			}
			set
			{
				this.OnPropertyChanging("new_submissiontype");
				this.SetAttributeValue("new_submissiontype", value);
				this.OnPropertyChanged("new_submissiontype");
			}
		}
		
		/// <summary>
		/// Lookup to the submitting party (Contact or Account).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_submitter")]
		public Microsoft.Xrm.Sdk.EntityReference new_submitter
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_submitter");
			}
			set
			{
				this.OnPropertyChanging("new_submitter");
				this.SetAttributeValue("new_submitter", value);
				this.OnPropertyChanged("new_submitter");
			}
		}
		
		/// <summary>
		/// Submission number as captured in platform through which grants are managed (Previously Output for Joule innovation grants).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_thirdpartysubmissionnumber")]
		public string new_thirdpartysubmissionnumber
		{
			get
			{
				return this.GetAttributeValue<string>("new_thirdpartysubmissionnumber");
			}
			set
			{
				this.OnPropertyChanging("new_thirdpartysubmissionnumber");
				this.SetAttributeValue("new_thirdpartysubmissionnumber", value);
				this.OnPropertyChanged("new_thirdpartysubmissionnumber");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Grant Submission
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual new_grantsubmission_statecode? statecode
		{
			get
			{
				return ((new_grantsubmission_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Grant Submission
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_grantsubmission_statuscode? statuscode
		{
			get
			{
				return ((new_grantsubmission_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N new_grantsubmission_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_grantsubmission_Annotations")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Annotation> new_grantsubmission_Annotations
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Annotation>("new_grantsubmission_Annotations", null);
			}
			set
			{
				this.OnPropertyChanging("new_grantsubmission_Annotations");
				this.SetRelatedEntities<CMA.Extensions.Model.Annotation>("new_grantsubmission_Annotations", null, value);
				this.OnPropertyChanged("new_grantsubmission_Annotations");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_grantsubmission_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_grantsubmission_createdby")]
		public CMA.Extensions.Model.SystemUser lk_new_grantsubmission_createdby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_grantsubmission_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_grantsubmission_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_grantsubmission_createdonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_grantsubmission_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_grantsubmission_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_grantsubmission_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_grantsubmission_modifiedby")]
		public CMA.Extensions.Model.SystemUser lk_new_grantsubmission_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_grantsubmission_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_grantsubmission_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_grantsubmission_modifiedonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_grantsubmission_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_grantsubmission_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 new_grantsubmission_customer_account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_submitter")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_grantsubmission_customer_account")]
		public CMA.Extensions.Model.Account new_grantsubmission_customer_account
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Account>("new_grantsubmission_customer_account", null);
			}
			set
			{
				this.OnPropertyChanging("new_grantsubmission_customer_account");
				this.SetRelatedEntity<CMA.Extensions.Model.Account>("new_grantsubmission_customer_account", null, value);
				this.OnPropertyChanged("new_grantsubmission_customer_account");
			}
		}
		
		/// <summary>
		/// N:1 new_grantsubmission_customer_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_submitter")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_grantsubmission_customer_contact")]
		public CMA.Extensions.Model.Contact new_grantsubmission_customer_contact
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Contact>("new_grantsubmission_customer_contact", null);
			}
			set
			{
				this.OnPropertyChanging("new_grantsubmission_customer_contact");
				this.SetRelatedEntity<CMA.Extensions.Model.Contact>("new_grantsubmission_customer_contact", null, value);
				this.OnPropertyChanged("new_grantsubmission_customer_contact");
			}
		}
		
		/// <summary>
		/// N:1 new_grantsubmission_grantprogram
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_grantprogramid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_grantsubmission_grantprogram")]
		public CMA.Extensions.Model.new_grantprogram new_grantsubmission_grantprogram
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_grantprogram>("new_grantsubmission_grantprogram", null);
			}
			set
			{
				this.OnPropertyChanging("new_grantsubmission_grantprogram");
				this.SetRelatedEntity<CMA.Extensions.Model.new_grantprogram>("new_grantsubmission_grantprogram", null, value);
				this.OnPropertyChanged("new_grantsubmission_grantprogram");
			}
		}
		
		/// <summary>
		/// N:1 user_new_grantsubmission
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_new_grantsubmission")]
		public CMA.Extensions.Model.SystemUser user_new_grantsubmission
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("user_new_grantsubmission", null);
			}
		}
	}
}
#pragma warning restore CS1591
