#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Status of the Contact Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_contacttype_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Contact Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_contacttype_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_contacttype")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class new_contacttype : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public new_contacttype() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_contacttype";
		
		public const string EntityLogicalCollectionName = "new_contacttypes";
		
		public const string EntitySetName = "new_contacttypes";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Unique autonumber value
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contacttype_id")]
		public string new_contacttype_id
		{
			get
			{
				return this.GetAttributeValue<string>("new_contacttype_id");
			}
			set
			{
				this.OnPropertyChanging("new_contacttype_id");
				this.SetAttributeValue("new_contacttype_id", value);
				this.OnPropertyChanged("new_contacttype_id");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contacttypeid")]
		public System.Nullable<System.Guid> new_contacttypeId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_contacttypeid");
			}
			set
			{
				this.OnPropertyChanging("new_contacttypeId");
				this.SetAttributeValue("new_contacttypeid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_contacttypeId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contacttypeid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.new_contacttypeId = value;
			}
		}
		
		/// <summary>
		/// English name referenced on portal pages based on language selection. Referenced in portal customizations.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_english")]
		public string new_English
		{
			get
			{
				return this.GetAttributeValue<string>("new_english");
			}
			set
			{
				this.OnPropertyChanging("new_English");
				this.SetAttributeValue("new_english", value);
				this.OnPropertyChanged("new_English");
			}
		}
		
		/// <summary>
		/// French name referenced on portal pages based on language selection. Referenced in portal customizations.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_french")]
		public string new_French
		{
			get
			{
				return this.GetAttributeValue<string>("new_french");
			}
			set
			{
				this.OnPropertyChanging("new_French");
				this.SetAttributeValue("new_french", value);
				this.OnPropertyChanged("new_French");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
		public string new_name
		{
			get
			{
				return this.GetAttributeValue<string>("new_name");
			}
			set
			{
				this.OnPropertyChanging("new_name");
				this.SetAttributeValue("new_name", value);
				this.OnPropertyChanged("new_name");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name_1033")]
		public string new_name_1033
		{
			get
			{
				return this.GetAttributeValue<string>("new_name_1033");
			}
			set
			{
				this.OnPropertyChanging("new_name_1033");
				this.SetAttributeValue("new_name_1033", value);
				this.OnPropertyChanged("new_name_1033");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name_1036")]
		public string new_name_1036
		{
			get
			{
				return this.GetAttributeValue<string>("new_name_1036");
			}
			set
			{
				this.OnPropertyChanging("new_name_1036");
				this.SetAttributeValue("new_name_1036", value);
				this.OnPropertyChanged("new_name_1036");
			}
		}
		
		/// <summary>
		/// Allows self-referential hierarchy of contact types (i.e. Types and sub-set of Sub-Types). Referenced in both CRM and portal customizations.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_parentypeid")]
		public Microsoft.Xrm.Sdk.EntityReference new_parentypeid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_parentypeid");
			}
			set
			{
				this.OnPropertyChanging("new_parentypeid");
				this.SetAttributeValue("new_parentypeid", value);
				this.OnPropertyChanged("new_parentypeid");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Status of the Contact Type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual new_contacttype_statecode? statecode
		{
			get
			{
				return ((new_contacttype_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Contact Type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_contacttype_statuscode? statuscode
		{
			get
			{
				return ((new_contacttype_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N new_contact_contactsubtypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_contact_contactsubtypeid")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Contact> new_contact_contactsubtypeid
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Contact>("new_contact_contactsubtypeid", null);
			}
			set
			{
				this.OnPropertyChanging("new_contact_contactsubtypeid");
				this.SetRelatedEntities<CMA.Extensions.Model.Contact>("new_contact_contactsubtypeid", null, value);
				this.OnPropertyChanged("new_contact_contactsubtypeid");
			}
		}
		
		/// <summary>
		/// 1:N new_contact_contacttypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_contact_contacttypeid")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Contact> new_contact_contacttypeid
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Contact>("new_contact_contacttypeid", null);
			}
			set
			{
				this.OnPropertyChanging("new_contact_contacttypeid");
				this.SetRelatedEntities<CMA.Extensions.Model.Contact>("new_contact_contacttypeid", null, value);
				this.OnPropertyChanged("new_contact_contacttypeid");
			}
		}
		
		/// <summary>
		/// 1:N new_membershippricingrule_contacttype
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_membershippricingrule_contacttype")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_membershippricingrule> new_membershippricingrule_contacttype
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_membershippricingrule>("new_membershippricingrule_contacttype", null);
			}
			set
			{
				this.OnPropertyChanging("new_membershippricingrule_contacttype");
				this.SetRelatedEntities<CMA.Extensions.Model.new_membershippricingrule>("new_membershippricingrule_contacttype", null, value);
				this.OnPropertyChanged("new_membershippricingrule_contacttype");
			}
		}
		
		/// <summary>
		/// 1:N new_new_contacttype_new_contacttype_parentypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_contacttype_new_contacttype_parentypeid", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_contacttype> Referencednew_new_contacttype_new_contacttype_parentypeid
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_contacttype>("new_new_contacttype_new_contacttype_parentypeid", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referencednew_new_contacttype_new_contacttype_parentypeid");
				this.SetRelatedEntities<CMA.Extensions.Model.new_contacttype>("new_new_contacttype_new_contacttype_parentypeid", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencednew_new_contacttype_new_contacttype_parentypeid");
			}
		}
		
		/// <summary>
		/// 1:N new_onlineapplication_carreeerstatuscontacttype
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_onlineapplication_carreeerstatuscontacttype")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_onlineapplication> new_onlineapplication_carreeerstatuscontacttype
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_onlineapplication>("new_onlineapplication_carreeerstatuscontacttype", null);
			}
			set
			{
				this.OnPropertyChanging("new_onlineapplication_carreeerstatuscontacttype");
				this.SetRelatedEntities<CMA.Extensions.Model.new_onlineapplication>("new_onlineapplication_carreeerstatuscontacttype", null, value);
				this.OnPropertyChanged("new_onlineapplication_carreeerstatuscontacttype");
			}
		}
		
		/// <summary>
		/// N:N new_subscription_contacttype_for_Portal
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_subscription_contacttype_for_Portal")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_subscription> new_subscription_contacttype_for_Portal
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_subscription>("new_subscription_contacttype_for_Portal", null);
			}
			set
			{
				this.OnPropertyChanging("new_subscription_contacttype_for_Portal");
				this.SetRelatedEntities<CMA.Extensions.Model.new_subscription>("new_subscription_contacttype_for_Portal", null, value);
				this.OnPropertyChanged("new_subscription_contacttype_for_Portal");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_contacttype_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_contacttype_createdby")]
		public CMA.Extensions.Model.SystemUser lk_new_contacttype_createdby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_contacttype_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_contacttype_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_contacttype_createdonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_contacttype_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_contacttype_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_contacttype_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_contacttype_modifiedby")]
		public CMA.Extensions.Model.SystemUser lk_new_contacttype_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_contacttype_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_contacttype_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_contacttype_modifiedonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_contacttype_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_contacttype_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 new_new_contacttype_new_contacttype_parentypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_parentypeid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_contacttype_new_contacttype_parentypeid", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public CMA.Extensions.Model.new_contacttype Referencingnew_new_contacttype_new_contacttype_parentypeid
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_contacttype>("new_new_contacttype_new_contacttype_parentypeid", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.OnPropertyChanging("Referencingnew_new_contacttype_new_contacttype_parentypeid");
				this.SetRelatedEntity<CMA.Extensions.Model.new_contacttype>("new_new_contacttype_new_contacttype_parentypeid", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingnew_new_contacttype_new_contacttype_parentypeid");
			}
		}
	}
}
#pragma warning restore CS1591
