#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Status of the Attendee Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_attendeetype_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Attendee Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_attendeetype_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_attendeetype")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class new_attendeetype : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public new_attendeetype() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_attendeetype";
		
		public const string EntityLogicalCollectionName = "new_attendeetypes";
		
		public const string EntitySetName = "new_attendeetypes";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Unique autonumber value
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_attendeetype_id")]
		public string new_attendeetype_id
		{
			get
			{
				return this.GetAttributeValue<string>("new_attendeetype_id");
			}
			set
			{
				this.OnPropertyChanging("new_attendeetype_id");
				this.SetAttributeValue("new_attendeetype_id", value);
				this.OnPropertyChanged("new_attendeetype_id");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_attendeetypeid")]
		public System.Nullable<System.Guid> new_attendeetypeId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_attendeetypeid");
			}
			set
			{
				this.OnPropertyChanging("new_attendeetypeId");
				this.SetAttributeValue("new_attendeetypeid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_attendeetypeId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_attendeetypeid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.new_attendeetypeId = value;
			}
		}
		
		/// <summary>
		/// English name, added to data model in case of future exposure on member-facing portal / adherence to custom design determined when creating Contact Type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_english")]
		public string new_english
		{
			get
			{
				return this.GetAttributeValue<string>("new_english");
			}
			set
			{
				this.OnPropertyChanging("new_english");
				this.SetAttributeValue("new_english", value);
				this.OnPropertyChanged("new_english");
			}
		}
		
		/// <summary>
		/// French name, added to data model in case of future exposure on member-facing portal / adherence to custom design determined when creating Contact Type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_french")]
		public string new_french
		{
			get
			{
				return this.GetAttributeValue<string>("new_french");
			}
			set
			{
				this.OnPropertyChanging("new_french");
				this.SetAttributeValue("new_french", value);
				this.OnPropertyChanged("new_french");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
		public string new_name
		{
			get
			{
				return this.GetAttributeValue<string>("new_name");
			}
			set
			{
				this.OnPropertyChanging("new_name");
				this.SetAttributeValue("new_name", value);
				this.OnPropertyChanged("new_name");
			}
		}
		
		/// <summary>
		/// Lookup field to Attendee Types, supports self-referential hierarchy (i.e. Types have sub-sets of Sub-Types).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_parenttypeid")]
		public Microsoft.Xrm.Sdk.EntityReference new_parenttypeid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_parenttypeid");
			}
			set
			{
				this.OnPropertyChanging("new_parenttypeid");
				this.SetAttributeValue("new_parenttypeid", value);
				this.OnPropertyChanged("new_parenttypeid");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Status of the Attendee Type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual new_attendeetype_statecode? statecode
		{
			get
			{
				return ((new_attendeetype_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Attendee Type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_attendeetype_statuscode? statuscode
		{
			get
			{
				return ((new_attendeetype_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N new_attendee_attendeesubtypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_attendee_attendeesubtypeid")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_eventattendee> new_attendee_attendeesubtypeid
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_eventattendee>("new_attendee_attendeesubtypeid", null);
			}
			set
			{
				this.OnPropertyChanging("new_attendee_attendeesubtypeid");
				this.SetRelatedEntities<CMA.Extensions.Model.new_eventattendee>("new_attendee_attendeesubtypeid", null, value);
				this.OnPropertyChanged("new_attendee_attendeesubtypeid");
			}
		}
		
		/// <summary>
		/// 1:N new_attendeetype_parenttypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_attendeetype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_attendeetype> Referencednew_attendeetype_parenttypeid
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_attendeetype>("new_attendeetype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referencednew_attendeetype_parenttypeid");
				this.SetRelatedEntities<CMA.Extensions.Model.new_attendeetype>("new_attendeetype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencednew_attendeetype_parenttypeid");
			}
		}
		
		/// <summary>
		/// 1:N new_eventattendee_attendeetypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_eventattendee_attendeetypeid")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.new_eventattendee> new_eventattendee_attendeetypeid
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.new_eventattendee>("new_eventattendee_attendeetypeid", null);
			}
			set
			{
				this.OnPropertyChanging("new_eventattendee_attendeetypeid");
				this.SetRelatedEntities<CMA.Extensions.Model.new_eventattendee>("new_eventattendee_attendeetypeid", null, value);
				this.OnPropertyChanged("new_eventattendee_attendeetypeid");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_attendeetype_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_attendeetype_createdby")]
		public CMA.Extensions.Model.SystemUser lk_new_attendeetype_createdby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_attendeetype_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_attendeetype_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_attendeetype_createdonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_attendeetype_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_attendeetype_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_attendeetype_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_attendeetype_modifiedby")]
		public CMA.Extensions.Model.SystemUser lk_new_attendeetype_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_attendeetype_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_attendeetype_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_attendeetype_modifiedonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_attendeetype_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_attendeetype_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 new_attendeetype_parenttypeid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_parenttypeid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_attendeetype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public CMA.Extensions.Model.new_attendeetype Referencingnew_attendeetype_parenttypeid
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_attendeetype>("new_attendeetype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.OnPropertyChanging("Referencingnew_attendeetype_parenttypeid");
				this.SetRelatedEntity<CMA.Extensions.Model.new_attendeetype>("new_attendeetype_parenttypeid", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingnew_attendeetype_parenttypeid");
			}
		}
	}
}
#pragma warning restore CS1591
