#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Status of the Physician Specialty
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_physicianspecialty_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Physician Specialty
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_physicianspecialty_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Links the Specialty to the Contact entity and captures data about the link (e.g., date the specialty was obtained, primary specialty)
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_physicianspecialty")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class new_physicianspecialty : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public new_physicianspecialty() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_physicianspecialty";
		
		public const string EntityLogicalCollectionName = "new_physicianspecialties";
		
		public const string EntitySetName = "new_physicianspecialties";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Indicates the user that created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Indicates the date and time the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Indicates the user on behalf of whom the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Indicates the user that modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Indicates the date and time the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Indicates the user on behalf of whom the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Indicates the organization (i.e. RCPSC, CFPC) that has certified the physician in question with the specialty represented by the record.  Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_certbodyaccountid")]
		public Microsoft.Xrm.Sdk.EntityReference new_certbodyaccountid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_certbodyaccountid");
			}
			set
			{
				this.OnPropertyChanging("new_certbodyaccountid");
				this.SetAttributeValue("new_certbodyaccountid", value);
				this.OnPropertyChanged("new_certbodyaccountid");
			}
		}
		
		/// <summary>
		/// Indicates the physician to whom the specialty is being associated through the creation of the Physician Specialty record. Set programmatically when record is created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contactid")]
		public Microsoft.Xrm.Sdk.EntityReference new_ContactID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_contactid");
			}
			set
			{
				this.OnPropertyChanging("new_ContactID");
				this.SetAttributeValue("new_contactid", value);
				this.OnPropertyChanged("new_ContactID");
			}
		}
		
		/// <summary>
		/// Candidate for deletion - no longer used.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_englishname")]
		public string new_englishname
		{
			get
			{
				return this.GetAttributeValue<string>("new_englishname");
			}
			set
			{
				this.OnPropertyChanging("new_englishname");
				this.SetAttributeValue("new_englishname", value);
				this.OnPropertyChanged("new_englishname");
			}
		}
		
		/// <summary>
		/// Candidate for deletion - no longer used.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_frenchname")]
		public string new_frenchname
		{
			get
			{
				return this.GetAttributeValue<string>("new_frenchname");
			}
			set
			{
				this.OnPropertyChanging("new_frenchname");
				this.SetAttributeValue("new_frenchname", value);
				this.OnPropertyChanged("new_frenchname");
			}
		}
		
		/// <summary>
		/// Set programmatically, concatenated value of "[Contact Name] - [Specialty Name]".
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
		public string new_name
		{
			get
			{
				return this.GetAttributeValue<string>("new_name");
			}
			set
			{
				this.OnPropertyChanging("new_name");
				this.SetAttributeValue("new_name", value);
				this.OnPropertyChanged("new_name");
			}
		}
		
		/// <summary>
		/// Unique autonumber value
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_physicianspecialty_id")]
		public string new_physicianspecialty_id
		{
			get
			{
				return this.GetAttributeValue<string>("new_physicianspecialty_id");
			}
			set
			{
				this.OnPropertyChanging("new_physicianspecialty_id");
				this.SetAttributeValue("new_physicianspecialty_id", value);
				this.OnPropertyChanged("new_physicianspecialty_id");
			}
		}
		
		/// <summary>
		/// Primary key, for internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_physicianspecialtyid")]
		public System.Nullable<System.Guid> new_physicianspecialtyId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_physicianspecialtyid");
			}
			set
			{
				this.OnPropertyChanging("new_physicianspecialtyId");
				this.SetAttributeValue("new_physicianspecialtyid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_physicianspecialtyId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_physicianspecialtyid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.new_physicianspecialtyId = value;
			}
		}
		
		/// <summary>
		/// Indicates whether or not the associated Specialty describes the work for which the associated physician is known for OR most prominently certified to perform. Limit of one Primary record per contact.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_primary")]
		public System.Nullable<bool> new_primary
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_primary");
			}
			set
			{
				this.OnPropertyChanging("new_primary");
				this.SetAttributeValue("new_primary", value);
				this.OnPropertyChanged("new_primary");
			}
		}
		
		/// <summary>
		/// Indicates whether or not the associated Specialty describes the work that the associated physician performs most regularly. No limit to the number of functional specialties per contact.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_primarycompetency")]
		public System.Nullable<bool> new_PrimaryCompetency
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_primarycompetency");
			}
			set
			{
				this.OnPropertyChanging("new_PrimaryCompetency");
				this.SetAttributeValue("new_primarycompetency", value);
				this.OnPropertyChanged("new_PrimaryCompetency");
			}
		}
		
		/// <summary>
		/// Link to Specialty record. Set manually. Referred to in custom logic that filters the list of available Specialties based on selection in the Type field.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_specialtyid")]
		public Microsoft.Xrm.Sdk.EntityReference new_SpecialtyID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_specialtyid");
			}
			set
			{
				this.OnPropertyChanging("new_SpecialtyID");
				this.SetAttributeValue("new_specialtyid", value);
				this.OnPropertyChanged("new_SpecialtyID");
			}
		}
		
		/// <summary>
		/// Indicates what category of specialty the record represents. Value determines available specialties from which to select in the Specialty Name field (of the same Type). Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_specialtytypecode")]
		public virtual new_specialtytypecode? new_SpecialtyTypeCode
		{
			get
			{
				return ((new_specialtytypecode?)(EntityOptionSetEnum.GetEnum(this, "new_specialtytypecode")));
			}
			set
			{
				this.OnPropertyChanging("new_SpecialtyTypeCode");
				this.SetAttributeValue("new_specialtytypecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_SpecialtyTypeCode");
			}
		}
		
		/// <summary>
		/// Indicates the year that the physician was certified as a specialist in the specialty reflected by the record. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_yearobtained")]
		public string new_yearobtained
		{
			get
			{
				return this.GetAttributeValue<string>("new_yearobtained");
			}
			set
			{
				this.OnPropertyChanging("new_yearobtained");
				this.SetAttributeValue("new_yearobtained", value);
				this.OnPropertyChanged("new_yearobtained");
			}
		}
		
		/// <summary>
		/// Internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// OOTB owner field, not used as part of current process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// OOTB status field.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual new_physicianspecialty_statecode? statecode
		{
			get
			{
				return ((new_physicianspecialty_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// OOTB status reason field.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_physicianspecialty_statuscode? statuscode
		{
			get
			{
				return ((new_physicianspecialty_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N new_physicianspecialty_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_physicianspecialty_Annotations")]
		public System.Collections.Generic.IEnumerable<CMA.Extensions.Model.Annotation> new_physicianspecialty_Annotations
		{
			get
			{
				return this.GetRelatedEntities<CMA.Extensions.Model.Annotation>("new_physicianspecialty_Annotations", null);
			}
			set
			{
				this.OnPropertyChanging("new_physicianspecialty_Annotations");
				this.SetRelatedEntities<CMA.Extensions.Model.Annotation>("new_physicianspecialty_Annotations", null, value);
				this.OnPropertyChanged("new_physicianspecialty_Annotations");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_physicianspecialty_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_physicianspecialty_createdby")]
		public CMA.Extensions.Model.SystemUser lk_new_physicianspecialty_createdby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_physicianspecialty_createdby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_new_physicianspecialty_createdby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_physicianspecialty_createdby", null, value);
				this.OnPropertyChanged("lk_new_physicianspecialty_createdby");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_physicianspecialty_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_physicianspecialty_createdonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_physicianspecialty_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_physicianspecialty_createdonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_new_physicianspecialty_createdonbehalfby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_physicianspecialty_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_new_physicianspecialty_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_physicianspecialty_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_physicianspecialty_modifiedby")]
		public CMA.Extensions.Model.SystemUser lk_new_physicianspecialty_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_physicianspecialty_modifiedby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_new_physicianspecialty_modifiedby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_physicianspecialty_modifiedby", null, value);
				this.OnPropertyChanged("lk_new_physicianspecialty_modifiedby");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_physicianspecialty_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_physicianspecialty_modifiedonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_physicianspecialty_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_physicianspecialty_modifiedonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_new_physicianspecialty_modifiedonbehalfby");
				this.SetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_physicianspecialty_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_new_physicianspecialty_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 new_account_physicianspecialty
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_certbodyaccountid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_account_physicianspecialty")]
		public CMA.Extensions.Model.Account new_account_physicianspecialty
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Account>("new_account_physicianspecialty", null);
			}
			set
			{
				this.OnPropertyChanging("new_account_physicianspecialty");
				this.SetRelatedEntity<CMA.Extensions.Model.Account>("new_account_physicianspecialty", null, value);
				this.OnPropertyChanged("new_account_physicianspecialty");
			}
		}
		
		/// <summary>
		/// N:1 new_contact_physicianspecialty
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_contactid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_contact_physicianspecialty")]
		public CMA.Extensions.Model.Contact new_contact_physicianspecialty
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Contact>("new_contact_physicianspecialty", null);
			}
			set
			{
				this.OnPropertyChanging("new_contact_physicianspecialty");
				this.SetRelatedEntity<CMA.Extensions.Model.Contact>("new_contact_physicianspecialty", null, value);
				this.OnPropertyChanged("new_contact_physicianspecialty");
			}
		}
		
		/// <summary>
		/// N:1 new_specialty_physicianspecialty
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_specialtyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_specialty_physicianspecialty")]
		public CMA.Extensions.Model.new_specialty new_specialty_physicianspecialty
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_specialty>("new_specialty_physicianspecialty", null);
			}
			set
			{
				this.OnPropertyChanging("new_specialty_physicianspecialty");
				this.SetRelatedEntity<CMA.Extensions.Model.new_specialty>("new_specialty_physicianspecialty", null, value);
				this.OnPropertyChanged("new_specialty_physicianspecialty");
			}
		}
		
		/// <summary>
		/// N:1 user_new_physicianspecialty
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_new_physicianspecialty")]
		public CMA.Extensions.Model.SystemUser user_new_physicianspecialty
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("user_new_physicianspecialty", null);
			}
		}
	}
}
#pragma warning restore CS1591
