#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Status of the CMA Flow Log
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_cmaflowlog_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the CMA Flow Log
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_cmaflowlog_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_cmaflowlog")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class new_CMAFlowLog : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public new_CMAFlowLog() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_cmaflowlog";
		
		public const string EntityLogicalCollectionName = "new_cmaflowlogs";
		
		public const string EntitySetName = "new_cmaflowlogs";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cmaflowlogid")]
		public System.Nullable<System.Guid> new_CMAFlowLogId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_cmaflowlogid");
			}
			set
			{
				this.OnPropertyChanging("new_CMAFlowLogId");
				this.SetAttributeValue("new_cmaflowlogid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_CMAFlowLogId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_cmaflowlogid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.new_CMAFlowLogId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_environment")]
		public Microsoft.Xrm.Sdk.EntityReference new_Environment
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_environment");
			}
			set
			{
				this.OnPropertyChanging("new_Environment");
				this.SetAttributeValue("new_environment", value);
				this.OnPropertyChanged("new_Environment");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_event")]
		public string new_Event
		{
			get
			{
				return this.GetAttributeValue<string>("new_event");
			}
			set
			{
				this.OnPropertyChanging("new_Event");
				this.SetAttributeValue("new_event", value);
				this.OnPropertyChanged("new_Event");
			}
		}
		
		/// <summary>
		/// Large Events
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_eventdetails")]
		public string new_EventDetails
		{
			get
			{
				return this.GetAttributeValue<string>("new_eventdetails");
			}
			set
			{
				this.OnPropertyChanging("new_EventDetails");
				this.SetAttributeValue("new_eventdetails", value);
				this.OnPropertyChanged("new_EventDetails");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
		public string new_Name
		{
			get
			{
				return this.GetAttributeValue<string>("new_name");
			}
			set
			{
				this.OnPropertyChanging("new_Name");
				this.SetAttributeValue("new_name", value);
				this.OnPropertyChanged("new_Name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_source")]
		public string new_Source
		{
			get
			{
				return this.GetAttributeValue<string>("new_source");
			}
			set
			{
				this.OnPropertyChanging("new_Source");
				this.SetAttributeValue("new_source", value);
				this.OnPropertyChanged("new_Source");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the CMA Flow Log
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual new_cmaflowlog_statecode? statecode
		{
			get
			{
				return ((new_cmaflowlog_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the CMA Flow Log
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_cmaflowlog_statuscode? statuscode
		{
			get
			{
				return ((new_cmaflowlog_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_cmaflowlog_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_cmaflowlog_createdby")]
		public CMA.Extensions.Model.SystemUser lk_new_cmaflowlog_createdby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_cmaflowlog_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_cmaflowlog_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_cmaflowlog_createdonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_cmaflowlog_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_cmaflowlog_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_cmaflowlog_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_cmaflowlog_modifiedby")]
		public CMA.Extensions.Model.SystemUser lk_new_cmaflowlog_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_cmaflowlog_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_cmaflowlog_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_cmaflowlog_modifiedonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_cmaflowlog_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_cmaflowlog_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 new_cmaflowlog_Environment_new_cmaflowconfiguration
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_environment")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_cmaflowlog_Environment_new_cmaflowconfiguration")]
		public CMA.Extensions.Model.new_CMAFlowConfiguration new_cmaflowlog_Environment_new_cmaflowconfiguration
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_CMAFlowConfiguration>("new_cmaflowlog_Environment_new_cmaflowconfiguration", null);
			}
			set
			{
				this.OnPropertyChanging("new_cmaflowlog_Environment_new_cmaflowconfiguration");
				this.SetRelatedEntity<CMA.Extensions.Model.new_CMAFlowConfiguration>("new_cmaflowlog_Environment_new_cmaflowconfiguration", null, value);
				this.OnPropertyChanged("new_cmaflowlog_Environment_new_cmaflowconfiguration");
			}
		}
		
		/// <summary>
		/// N:1 user_new_cmaflowlog
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_new_cmaflowlog")]
		public CMA.Extensions.Model.SystemUser user_new_cmaflowlog
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("user_new_cmaflowlog", null);
			}
		}
	}
}
#pragma warning restore CS1591
