#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Status of the Payment
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_payment_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Payment
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_payment_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Planned = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Received = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Submitted = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_payment")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class new_payment : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public new_payment() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "new_payment";
		
		public const string EntityLogicalCollectionName = "new_payments";
		
		public const string EntitySetName = "new_payments";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Unique identifier for Batch associated with Payment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_batchid")]
		public Microsoft.Xrm.Sdk.EntityReference new_BatchID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_batchid");
			}
			set
			{
				this.OnPropertyChanging("new_BatchID");
				this.SetAttributeValue("new_batchid", value);
				this.OnPropertyChanged("new_BatchID");
			}
		}
		
		/// <summary>
		/// Open text field to provide additional context to the payment record that can't otherwise be represented through structured data.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_comments")]
		public string new_Comments
		{
			get
			{
				return this.GetAttributeValue<string>("new_comments");
			}
			set
			{
				this.OnPropertyChanging("new_Comments");
				this.SetAttributeValue("new_comments", value);
				this.OnPropertyChanged("new_Comments");
			}
		}
		
		/// <summary>
		/// Indicates the type/brand of credit card with which the payment was made in cases of direct membership.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_creditcardtype")]
		public virtual new_paymentcreditcardtype? new_CreditCardType
		{
			get
			{
				return ((new_paymentcreditcardtype?)(EntityOptionSetEnum.GetEnum(this, "new_creditcardtype")));
			}
			set
			{
				this.OnPropertyChanging("new_CreditCardType");
				this.SetAttributeValue("new_creditcardtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_CreditCardType");
			}
		}
		
		/// <summary>
		/// Unique identifier for Online Application associated with Payment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_onlineapplicationid")]
		public Microsoft.Xrm.Sdk.EntityReference new_onlineapplicationid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_onlineapplicationid");
			}
			set
			{
				this.OnPropertyChanging("new_onlineapplicationid");
				this.SetAttributeValue("new_onlineapplicationid", value);
				this.OnPropertyChanged("new_onlineapplicationid");
			}
		}
		
		/// <summary>
		/// Unique identifier for Order associated with Payment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_orderid")]
		public Microsoft.Xrm.Sdk.EntityReference new_OrderID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_orderid");
			}
			set
			{
				this.OnPropertyChanging("new_OrderID");
				this.SetAttributeValue("new_orderid", value);
				this.OnPropertyChanged("new_OrderID");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_payment_id")]
		public string new_payment_id
		{
			get
			{
				return this.GetAttributeValue<string>("new_payment_id");
			}
			set
			{
				this.OnPropertyChanging("new_payment_id");
				this.SetAttributeValue("new_payment_id", value);
				this.OnPropertyChanged("new_payment_id");
			}
		}
		
		/// <summary>
		/// Dollar amount of the payment. Set programmatically.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentamount")]
		public Microsoft.Xrm.Sdk.Money new_PaymentAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_paymentamount");
			}
			set
			{
				this.OnPropertyChanging("new_PaymentAmount");
				this.SetAttributeValue("new_paymentamount", value);
				this.OnPropertyChanged("new_PaymentAmount");
			}
		}
		
		/// <summary>
		/// Value of the Payment Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentamount_base")]
		public Microsoft.Xrm.Sdk.Money new_paymentamount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("new_paymentamount_base");
			}
		}
		
		/// <summary>
		/// Unique identifier for Account associated with Payment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentfromaccountid")]
		public Microsoft.Xrm.Sdk.EntityReference new_PaymentfromAccountID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_paymentfromaccountid");
			}
			set
			{
				this.OnPropertyChanging("new_PaymentfromAccountID");
				this.SetAttributeValue("new_paymentfromaccountid", value);
				this.OnPropertyChanged("new_PaymentfromAccountID");
			}
		}
		
		/// <summary>
		/// Unique identifier for Contact associated with Payment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentfromcontactid")]
		public Microsoft.Xrm.Sdk.EntityReference new_PaymentfromContactID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_paymentfromcontactid");
			}
			set
			{
				this.OnPropertyChanging("new_PaymentfromContactID");
				this.SetAttributeValue("new_paymentfromcontactid", value);
				this.OnPropertyChanged("new_PaymentfromContactID");
			}
		}
		
		/// <summary>
		/// Indicates whether or not the payment this record represents came from another business unit within CMA in cases where funds may be accepted on behalf of other business units.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentfrominternal")]
		public System.Nullable<bool> new_PaymentfromInternal
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("new_paymentfrominternal");
			}
			set
			{
				this.OnPropertyChanging("new_PaymentfromInternal");
				this.SetAttributeValue("new_paymentfrominternal", value);
				this.OnPropertyChanged("new_PaymentfromInternal");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentid")]
		public System.Nullable<System.Guid> new_paymentId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("new_paymentid");
			}
			set
			{
				this.OnPropertyChanging("new_paymentId");
				this.SetAttributeValue("new_paymentid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("new_paymentId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.new_paymentId = value;
			}
		}
		
		/// <summary>
		/// Indicates the means through which the CMA has received or will receive funds for the membership purchase.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentmethod")]
		public virtual new_paymentmethod? new_PaymentMethod
		{
			get
			{
				return ((new_paymentmethod?)(EntityOptionSetEnum.GetEnum(this, "new_paymentmethod")));
			}
			set
			{
				this.OnPropertyChanging("new_PaymentMethod");
				this.SetAttributeValue("new_paymentmethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_PaymentMethod");
			}
		}
		
		/// <summary>
		/// Reference to Bambora when payment record is created as a result of a refund., populated programmatically with the value of the Transaction ID from the Bambora record. Refund customization dependent.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentreference")]
		public string new_PaymentReference
		{
			get
			{
				return this.GetAttributeValue<string>("new_paymentreference");
			}
			set
			{
				this.OnPropertyChanging("new_PaymentReference");
				this.SetAttributeValue("new_paymentreference", value);
				this.OnPropertyChanged("new_PaymentReference");
			}
		}
		
		/// <summary>
		/// Indicates whether the payment was created to reflect a purchase of membership for a physician from a direct PTMA or as a Member at Large. Set manually.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentsource")]
		public virtual new_paymentsource? new_paymentsource
		{
			get
			{
				return ((new_paymentsource?)(EntityOptionSetEnum.GetEnum(this, "new_paymentsource")));
			}
			set
			{
				this.OnPropertyChanging("new_paymentsource");
				this.SetAttributeValue("new_paymentsource", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("new_paymentsource");
			}
		}
		
		/// <summary>
		/// Unique identifier for Transaction associated with Payment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_transactionid")]
		public Microsoft.Xrm.Sdk.EntityReference new_TransactionID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_transactionid");
			}
			set
			{
				this.OnPropertyChanging("new_TransactionID");
				this.SetAttributeValue("new_transactionid", value);
				this.OnPropertyChanged("new_TransactionID");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual new_payment_statecode? statecode
		{
			get
			{
				return ((new_payment_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual new_payment_statuscode? statuscode
		{
			get
			{
				return ((new_payment_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 lk_new_payment_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_payment_createdby")]
		public CMA.Extensions.Model.SystemUser lk_new_payment_createdby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_payment_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_payment_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_payment_createdonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_payment_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_payment_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_payment_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_payment_modifiedby")]
		public CMA.Extensions.Model.SystemUser lk_new_payment_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_payment_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_new_payment_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_new_payment_modifiedonbehalfby")]
		public CMA.Extensions.Model.SystemUser lk_new_payment_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("lk_new_payment_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 new_account_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentfromaccountid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_account_payment")]
		public CMA.Extensions.Model.Account new_account_payment
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Account>("new_account_payment", null);
			}
			set
			{
				this.OnPropertyChanging("new_account_payment");
				this.SetRelatedEntity<CMA.Extensions.Model.Account>("new_account_payment", null, value);
				this.OnPropertyChanged("new_account_payment");
			}
		}
		
		/// <summary>
		/// N:1 new_batch_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_batchid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_batch_payment")]
		public CMA.Extensions.Model.new_batch new_batch_payment
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_batch>("new_batch_payment", null);
			}
			set
			{
				this.OnPropertyChanging("new_batch_payment");
				this.SetRelatedEntity<CMA.Extensions.Model.new_batch>("new_batch_payment", null, value);
				this.OnPropertyChanged("new_batch_payment");
			}
		}
		
		/// <summary>
		/// N:1 new_contact_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_paymentfromcontactid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_contact_payment")]
		public CMA.Extensions.Model.Contact new_contact_payment
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.Contact>("new_contact_payment", null);
			}
			set
			{
				this.OnPropertyChanging("new_contact_payment");
				this.SetRelatedEntity<CMA.Extensions.Model.Contact>("new_contact_payment", null, value);
				this.OnPropertyChanged("new_contact_payment");
			}
		}
		
		/// <summary>
		/// N:1 new_new_onlineapplication_new_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_onlineapplicationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_onlineapplication_new_payment")]
		public CMA.Extensions.Model.new_onlineapplication new_new_onlineapplication_new_payment
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_onlineapplication>("new_new_onlineapplication_new_payment", null);
			}
			set
			{
				this.OnPropertyChanging("new_new_onlineapplication_new_payment");
				this.SetRelatedEntity<CMA.Extensions.Model.new_onlineapplication>("new_new_onlineapplication_new_payment", null, value);
				this.OnPropertyChanged("new_new_onlineapplication_new_payment");
			}
		}
		
		/// <summary>
		/// N:1 new_salesorder_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_orderid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_salesorder_payment")]
		public CMA.Extensions.Model.SalesOrder new_salesorder_payment
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SalesOrder>("new_salesorder_payment", null);
			}
			set
			{
				this.OnPropertyChanging("new_salesorder_payment");
				this.SetRelatedEntity<CMA.Extensions.Model.SalesOrder>("new_salesorder_payment", null, value);
				this.OnPropertyChanged("new_salesorder_payment");
			}
		}
		
		/// <summary>
		/// N:1 new_transaction_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_transactionid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_transaction_payment")]
		public CMA.Extensions.Model.new_transaction new_transaction_payment
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.new_transaction>("new_transaction_payment", null);
			}
			set
			{
				this.OnPropertyChanging("new_transaction_payment");
				this.SetRelatedEntity<CMA.Extensions.Model.new_transaction>("new_transaction_payment", null, value);
				this.OnPropertyChanged("new_transaction_payment");
			}
		}
		
		/// <summary>
		/// N:1 user_new_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_new_payment")]
		public CMA.Extensions.Model.SystemUser user_new_payment
		{
			get
			{
				return this.GetRelatedEntity<CMA.Extensions.Model.SystemUser>("user_new_payment", null);
			}
		}
	}
}
#pragma warning restore CS1591
