#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_sentiment
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Positive = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Negative = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Neutral = 100000002,
	}
}
#pragma warning restore CS1591
