#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Candidate for deletion - created to support Azure B2C. Review statuses to categorize contacts created via B2C API.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_portalreviewstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReviewedApproved = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReviewedMerged = 100000002,
	}
}
#pragma warning restore CS1591
