#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Candidate for deletion - list of MD Company Names that could be added to a user record.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_usercompanynamefrench
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgencedassuranceMDlimite = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FiduciePriveMDlimite = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GestionMDlimite = 100000002,
	}
}
#pragma warning restore CS1591
