#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// List of categories that define the online portal usage by a Contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_contactonlineusage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Medium = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Casual = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Abandon = 100000004,
	}
}
#pragma warning restore CS1591
