#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_displayorder
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1 = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2 = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_3 = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_4 = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_5 = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_6 = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_7 = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_8 = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_9 = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_10 = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_11 = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_12 = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_13 = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_14 = 100000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_15 = 100000014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_16 = 100000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_17 = 100000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_18 = 100000017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_19 = 100000018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_20 = 100000019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_21 = 100000020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_22 = 100000021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_23 = 100000022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_24 = 100000023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_25 = 100000024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_26 = 100000025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_27 = 100000026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_28 = 100000027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_29 = 100000028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_30 = 100000029,
	}
}
#pragma warning restore CS1591
