#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Year Option Set
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_yearoptionset
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2059 = 2059,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2058 = 2058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2057 = 2057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2056 = 2056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2055 = 2055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2054 = 2054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2053 = 2053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2052 = 2052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2051 = 2051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2050 = 2050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2049 = 2049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2048 = 2048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2047 = 2047,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2046 = 2046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2045 = 2045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2044 = 2044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2043 = 2043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2042 = 2042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2041 = 2041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2040 = 2040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2039 = 2039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2038 = 2038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2037 = 2037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2036 = 2036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2035 = 2035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2034 = 2034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2033 = 2033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2032 = 2032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2031 = 2031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2030 = 2030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2029 = 2029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2028 = 2028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2027 = 2027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2026 = 2026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2025 = 2025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2024 = 2024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2023 = 2023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2022 = 2022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2021 = 2021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2020 = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2019 = 2019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2018 = 2018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2017 = 2017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2016 = 2016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2015 = 2015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2014 = 2014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2013 = 2013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2012 = 2012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2011 = 2011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2010 = 2010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2009 = 2009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2008 = 2008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2007 = 2007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2006 = 2006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2005 = 2005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2004 = 2004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2003 = 2003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2002 = 2002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2001 = 2001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2000 = 2000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1999 = 1999,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1998 = 1998,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1997 = 1997,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1996 = 1996,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1995 = 1995,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1994 = 1994,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1993 = 1993,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1992 = 1992,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1991 = 1991,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1990 = 1990,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1989 = 1989,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1988 = 1988,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1987 = 1987,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1986 = 1986,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1985 = 1985,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1984 = 1984,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1983 = 1983,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1982 = 1982,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1981 = 1981,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1980 = 1980,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1979 = 1979,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1978 = 1978,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1977 = 1977,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1976 = 1976,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1975 = 1975,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1974 = 1974,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1973 = 1973,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1972 = 1972,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1971 = 1971,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1970 = 1970,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1969 = 1969,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1968 = 1968,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1967 = 1967,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1966 = 1966,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1965 = 1965,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1964 = 1964,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1963 = 1963,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1962 = 1962,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1961 = 1961,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1960 = 1960,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1959 = 1959,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1958 = 1958,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1957 = 1957,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1956 = 1956,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1955 = 1955,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1954 = 1954,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1953 = 1953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1952 = 1952,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1951 = 1951,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1950 = 1950,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1949 = 1949,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1948 = 1948,
	}
}
#pragma warning restore CS1591
