#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// List of reasons why a Contact might decide to "opt-out" from receiving a subscription. Discontinued Reason entity is leveraged on CMA Membership Detail entity, but this list is exclusively for opts.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_optdiscontinuedreason
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Novalidaddresscantreachcontact = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Abroadnonactive = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Retirednonactive = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortalEmailAddressRemoval = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cancelled = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContactRequest = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deceased = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Householdreceivesit = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MembershipCategoryChange = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MembershipLapsedNotPaid = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnHold = 100000002,
	}
}
#pragma warning restore CS1591
