#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// List of French titles for the User entity. Not leveraged on Contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_userfrenchtitle
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AdjointadministratifrgionalAdjointeadministrativergionale = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrateurdeplacementsrgional = 100000025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Directeurdeportefeuille = 100000028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rceptionniste = 100000029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConseillerSuccessionsetfiducies = 100000030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrateurrgionaladjoint = 100000031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrateurdassurance = 100000032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conseillerenassurances = 100000033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Gestionnairedeportefeuilleadjoint = 100000034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Directeurdeportfefeuilleprincipal = 100000035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentdefiduciergional = 100000036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conseillerassociauxservicesdassurance = 100000037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChefdquipeAdministrationRgionale = 100000038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrateurdelquipedesservicesconsultatifs = 100000039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Spcialisteduservicelaclientle = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentterritorialdelaconformit = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ViceprsidentassociServicedegestiondepatrimoine = 100000027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Chefdelaconformit = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conseillerenplacement = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conseillerenplacementprincipal = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conseillreenplacement = 100000018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conseillreenplacementprincipale = 100000019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Coordonnateurdelquipeconsultative = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Coordonnatricedelquipeconsultative = 100000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Directeurrgion = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Directeurrgionadjoint = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DirecteurAdministrationrgionale = 100000022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Directricergionale = 100000020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Directricergionaleadjoint = 100000021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DirectriceAdministrationrgionale = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Planificateurfinancier = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Planificatricefinancire = 100000014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reprsentantducentredecourtage = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reprsentanteducentredecourtage = 100000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Spcialisteresponsabledesmdecinsendbutdecarrire = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Viceprsidentrgional = 100000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Viceprsidentergionale = 100000023,
	}
}
#pragma warning restore CS1591
