#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Used in Group field on Specialty record. As of 2020, data not consistently maintained. Data maintained manually
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_specialtygroup
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Anesthesia = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BacteriologyandMicrobiology = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dermatology = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmergencyMedicine = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FamilyPhysician = 100000020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GeneralSurgery = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalMedicine = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NeurologyandPsychiatry = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NuclearMedicine = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ObstetricsandGynecology = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OccupationalMedicine = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Opthalmology = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrthopedicSurgery = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Otolaryngology = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PathologyandImmunology = 100000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pediatrics = 100000014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhysicalMedicineandRehabilitation = 100000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PublicHealth = 100000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Radiology = 100000017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UrologyandNephrology = 100000018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 100000019,
	}
}
#pragma warning restore CS1591
