#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// List of practice locations that do not have PTMAs, for use in Application streaming (direct vs indirect). Heavily referenced in critical member-facing customization.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_locationofpractice
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quebec = 100000038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnitedStates = 100000232,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 100000002,
	}
}
#pragma warning restore CS1591
