#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// corresponds to campaign type Co-Branding
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_campaignsubtype_100000003
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MembershipAcquisitionRenewal = 100000001,
	}
}
#pragma warning restore CS1591
