#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// Superset of campaign sub-types
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_campaignsubtypemasterlist
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ClientNotification = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContactPrograms = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cruises = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExhibitsandConferences = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JournalDistribution = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LapsedMember = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MembershipAcquisitionRenewal = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductServiceLaunches = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResidentOrientation = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StudentOrientation = 100000002,
	}
}
#pragma warning restore CS1591
