#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// List of types of discounts which could be applied to a sale made by CMA. Adds context to Transaction, Membership Details, and Order Products.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_discountcategory
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DivisionDecision = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ForeignCurrency = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Guest = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GuestSpeakerSponsor = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GuestSpouseCompanion = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GuestYouth = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MaternityPaternityLeave = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MDLoyaltyProgram = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Member = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PromotionalManualDiscount = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Proration = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resident = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Student = 100000003,
	}
}
#pragma warning restore CS1591
