#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMA.Extensions.Model
{
	
	
	/// <summary>
	/// List of internal CMA business units that could be the client for an event.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum new_eventinternalclient
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExecutiveOffice = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AdvocacyandPolicy = 100000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CMAFoundation = 100000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CMAH2018 = 100000017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CommunityandMemberEngagement = 100000018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CorporateServices = 100000019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnterpriseMarketingandCommunications = 100000020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Innovation = 100000021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternationalHealth = 100000022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Investco = 100000023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LegalandGovernance = 100000024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhysicianHealthandWellness = 100000025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Strategy = 100000026,
	}
}
#pragma warning restore CS1591
